//! Dashboard data, mirrored from the shadcn `dashboard-01` block.
//!
//! Generated from the upstream chart/table sources: 91 daily chart
//! points (Apr 1 - Jun 30, 2024) and the 68 table rows.

pub const Day = struct {
    label: []const u8,
    desktop: u32,
    mobile: u32,

    /// The stacked total, what the top area of the chart outlines.
    pub fn total(self: Day) u32 {
        return self.desktop + self.mobile;
    }
};

pub const DAYS = [_]Day{
    .{ .label = "Apr 1", .desktop = 222, .mobile = 150 },
    .{ .label = "Apr 2", .desktop = 97, .mobile = 180 },
    .{ .label = "Apr 3", .desktop = 167, .mobile = 120 },
    .{ .label = "Apr 4", .desktop = 242, .mobile = 260 },
    .{ .label = "Apr 5", .desktop = 373, .mobile = 290 },
    .{ .label = "Apr 6", .desktop = 301, .mobile = 340 },
    .{ .label = "Apr 7", .desktop = 245, .mobile = 180 },
    .{ .label = "Apr 8", .desktop = 409, .mobile = 320 },
    .{ .label = "Apr 9", .desktop = 59, .mobile = 110 },
    .{ .label = "Apr 10", .desktop = 261, .mobile = 190 },
    .{ .label = "Apr 11", .desktop = 327, .mobile = 350 },
    .{ .label = "Apr 12", .desktop = 292, .mobile = 210 },
    .{ .label = "Apr 13", .desktop = 342, .mobile = 380 },
    .{ .label = "Apr 14", .desktop = 137, .mobile = 220 },
    .{ .label = "Apr 15", .desktop = 120, .mobile = 170 },
    .{ .label = "Apr 16", .desktop = 138, .mobile = 190 },
    .{ .label = "Apr 17", .desktop = 446, .mobile = 360 },
    .{ .label = "Apr 18", .desktop = 364, .mobile = 410 },
    .{ .label = "Apr 19", .desktop = 243, .mobile = 180 },
    .{ .label = "Apr 20", .desktop = 89, .mobile = 150 },
    .{ .label = "Apr 21", .desktop = 137, .mobile = 200 },
    .{ .label = "Apr 22", .desktop = 224, .mobile = 170 },
    .{ .label = "Apr 23", .desktop = 138, .mobile = 230 },
    .{ .label = "Apr 24", .desktop = 387, .mobile = 290 },
    .{ .label = "Apr 25", .desktop = 215, .mobile = 250 },
    .{ .label = "Apr 26", .desktop = 75, .mobile = 130 },
    .{ .label = "Apr 27", .desktop = 383, .mobile = 420 },
    .{ .label = "Apr 28", .desktop = 122, .mobile = 180 },
    .{ .label = "Apr 29", .desktop = 315, .mobile = 240 },
    .{ .label = "Apr 30", .desktop = 454, .mobile = 380 },
    .{ .label = "May 1", .desktop = 165, .mobile = 220 },
    .{ .label = "May 2", .desktop = 293, .mobile = 310 },
    .{ .label = "May 3", .desktop = 247, .mobile = 190 },
    .{ .label = "May 4", .desktop = 385, .mobile = 420 },
    .{ .label = "May 5", .desktop = 481, .mobile = 390 },
    .{ .label = "May 6", .desktop = 498, .mobile = 520 },
    .{ .label = "May 7", .desktop = 388, .mobile = 300 },
    .{ .label = "May 8", .desktop = 149, .mobile = 210 },
    .{ .label = "May 9", .desktop = 227, .mobile = 180 },
    .{ .label = "May 10", .desktop = 293, .mobile = 330 },
    .{ .label = "May 11", .desktop = 335, .mobile = 270 },
    .{ .label = "May 12", .desktop = 197, .mobile = 240 },
    .{ .label = "May 13", .desktop = 197, .mobile = 160 },
    .{ .label = "May 14", .desktop = 448, .mobile = 490 },
    .{ .label = "May 15", .desktop = 473, .mobile = 380 },
    .{ .label = "May 16", .desktop = 338, .mobile = 400 },
    .{ .label = "May 17", .desktop = 499, .mobile = 420 },
    .{ .label = "May 18", .desktop = 315, .mobile = 350 },
    .{ .label = "May 19", .desktop = 235, .mobile = 180 },
    .{ .label = "May 20", .desktop = 177, .mobile = 230 },
    .{ .label = "May 21", .desktop = 82, .mobile = 140 },
    .{ .label = "May 22", .desktop = 81, .mobile = 120 },
    .{ .label = "May 23", .desktop = 252, .mobile = 290 },
    .{ .label = "May 24", .desktop = 294, .mobile = 220 },
    .{ .label = "May 25", .desktop = 201, .mobile = 250 },
    .{ .label = "May 26", .desktop = 213, .mobile = 170 },
    .{ .label = "May 27", .desktop = 420, .mobile = 460 },
    .{ .label = "May 28", .desktop = 233, .mobile = 190 },
    .{ .label = "May 29", .desktop = 78, .mobile = 130 },
    .{ .label = "May 30", .desktop = 340, .mobile = 280 },
    .{ .label = "May 31", .desktop = 178, .mobile = 230 },
    .{ .label = "Jun 1", .desktop = 178, .mobile = 200 },
    .{ .label = "Jun 2", .desktop = 470, .mobile = 410 },
    .{ .label = "Jun 3", .desktop = 103, .mobile = 160 },
    .{ .label = "Jun 4", .desktop = 439, .mobile = 380 },
    .{ .label = "Jun 5", .desktop = 88, .mobile = 140 },
    .{ .label = "Jun 6", .desktop = 294, .mobile = 250 },
    .{ .label = "Jun 7", .desktop = 323, .mobile = 370 },
    .{ .label = "Jun 8", .desktop = 385, .mobile = 320 },
    .{ .label = "Jun 9", .desktop = 438, .mobile = 480 },
    .{ .label = "Jun 10", .desktop = 155, .mobile = 200 },
    .{ .label = "Jun 11", .desktop = 92, .mobile = 150 },
    .{ .label = "Jun 12", .desktop = 492, .mobile = 420 },
    .{ .label = "Jun 13", .desktop = 81, .mobile = 130 },
    .{ .label = "Jun 14", .desktop = 426, .mobile = 380 },
    .{ .label = "Jun 15", .desktop = 307, .mobile = 350 },
    .{ .label = "Jun 16", .desktop = 371, .mobile = 310 },
    .{ .label = "Jun 17", .desktop = 475, .mobile = 520 },
    .{ .label = "Jun 18", .desktop = 107, .mobile = 170 },
    .{ .label = "Jun 19", .desktop = 341, .mobile = 290 },
    .{ .label = "Jun 20", .desktop = 408, .mobile = 450 },
    .{ .label = "Jun 21", .desktop = 169, .mobile = 210 },
    .{ .label = "Jun 22", .desktop = 317, .mobile = 270 },
    .{ .label = "Jun 23", .desktop = 480, .mobile = 530 },
    .{ .label = "Jun 24", .desktop = 132, .mobile = 180 },
    .{ .label = "Jun 25", .desktop = 141, .mobile = 190 },
    .{ .label = "Jun 26", .desktop = 434, .mobile = 380 },
    .{ .label = "Jun 27", .desktop = 448, .mobile = 490 },
    .{ .label = "Jun 28", .desktop = 149, .mobile = 200 },
    .{ .label = "Jun 29", .desktop = 103, .mobile = 160 },
    .{ .label = "Jun 30", .desktop = 446, .mobile = 400 },
};

pub const Status = enum { done, in_process };

pub const Row = struct {
    id: u32,
    header: []const u8,
    section_type: []const u8,
    status: Status,
    target: []const u8,
    limit: []const u8,
    reviewer: []const u8,
};

pub const ROWS = [_]Row{
    .{ .id = 1,  .header = "Cover page",                                      .section_type = "Cover page",        .status = .in_process, .target = "18", .limit = "5",  .reviewer = "Eddie Lake" },
    .{ .id = 2,  .header = "Table of contents",                               .section_type = "Table of contents", .status = .done,       .target = "29", .limit = "24", .reviewer = "Eddie Lake" },
    .{ .id = 3,  .header = "Executive summary",                               .section_type = "Narrative",         .status = .done,       .target = "10", .limit = "13", .reviewer = "Eddie Lake" },
    .{ .id = 4,  .header = "Technical approach",                              .section_type = "Narrative",         .status = .done,       .target = "27", .limit = "23", .reviewer = "Jamik Tashpulatov" },
    .{ .id = 5,  .header = "Design",                                          .section_type = "Narrative",         .status = .in_process, .target = "2",  .limit = "16", .reviewer = "Jamik Tashpulatov" },
    .{ .id = 6,  .header = "Capabilities",                                    .section_type = "Narrative",         .status = .in_process, .target = "20", .limit = "8",  .reviewer = "Jamik Tashpulatov" },
    .{ .id = 7,  .header = "Integration with existing systems",               .section_type = "Narrative",         .status = .in_process, .target = "19", .limit = "21", .reviewer = "Jamik Tashpulatov" },
    .{ .id = 8,  .header = "Innovation and Advantages",                       .section_type = "Narrative",         .status = .done,       .target = "25", .limit = "26", .reviewer = "Assign reviewer" },
    .{ .id = 9,  .header = "Overview of EMR's Innovative Solutions",          .section_type = "Technical content", .status = .done,       .target = "7",  .limit = "23", .reviewer = "Assign reviewer" },
    .{ .id = 10, .header = "Advanced Algorithms and Machine Learning",        .section_type = "Narrative",         .status = .done,       .target = "30", .limit = "28", .reviewer = "Assign reviewer" },
    .{ .id = 11, .header = "Adaptive Communication Protocols",                .section_type = "Narrative",         .status = .done,       .target = "9",  .limit = "31", .reviewer = "Assign reviewer" },
    .{ .id = 12, .header = "Advantages Over Current Technologies",            .section_type = "Narrative",         .status = .done,       .target = "12", .limit = "0",  .reviewer = "Assign reviewer" },
    .{ .id = 13, .header = "Past Performance",                                .section_type = "Narrative",         .status = .done,       .target = "22", .limit = "33", .reviewer = "Assign reviewer" },
    .{ .id = 14, .header = "Customer Feedback and Satisfaction Levels",       .section_type = "Narrative",         .status = .done,       .target = "15", .limit = "34", .reviewer = "Assign reviewer" },
    .{ .id = 15, .header = "Implementation Challenges and Solutions",         .section_type = "Narrative",         .status = .done,       .target = "3",  .limit = "35", .reviewer = "Assign reviewer" },
    .{ .id = 16, .header = "Security Measures and Data Protection Policies",  .section_type = "Narrative",         .status = .in_process, .target = "6",  .limit = "36", .reviewer = "Assign reviewer" },
    .{ .id = 17, .header = "Scalability and Future Proofing",                 .section_type = "Narrative",         .status = .done,       .target = "4",  .limit = "37", .reviewer = "Assign reviewer" },
    .{ .id = 18, .header = "Cost-Benefit Analysis",                           .section_type = "Plain language",    .status = .done,       .target = "14", .limit = "38", .reviewer = "Assign reviewer" },
    .{ .id = 19, .header = "User Training and Onboarding Experience",         .section_type = "Narrative",         .status = .done,       .target = "17", .limit = "39", .reviewer = "Assign reviewer" },
    .{ .id = 20, .header = "Future Development Roadmap",                      .section_type = "Narrative",         .status = .done,       .target = "11", .limit = "40", .reviewer = "Assign reviewer" },
    .{ .id = 21, .header = "System Architecture Overview",                    .section_type = "Technical content", .status = .in_process, .target = "24", .limit = "18", .reviewer = "Maya Johnson" },
    .{ .id = 22, .header = "Risk Management Plan",                            .section_type = "Narrative",         .status = .done,       .target = "15", .limit = "22", .reviewer = "Carlos Rodriguez" },
    .{ .id = 23, .header = "Compliance Documentation",                        .section_type = "Legal",             .status = .in_process, .target = "31", .limit = "27", .reviewer = "Sarah Chen" },
    .{ .id = 24, .header = "API Documentation",                               .section_type = "Technical content", .status = .done,       .target = "8",  .limit = "12", .reviewer = "Raj Patel" },
    .{ .id = 25, .header = "User Interface Mockups",                          .section_type = "Visual",            .status = .in_process, .target = "19", .limit = "25", .reviewer = "Leila Ahmadi" },
    .{ .id = 26, .header = "Database Schema",                                 .section_type = "Technical content", .status = .done,       .target = "22", .limit = "20", .reviewer = "Thomas Wilson" },
    .{ .id = 27, .header = "Testing Methodology",                             .section_type = "Technical content", .status = .in_process, .target = "17", .limit = "14", .reviewer = "Assign reviewer" },
    .{ .id = 28, .header = "Deployment Strategy",                             .section_type = "Narrative",         .status = .done,       .target = "26", .limit = "30", .reviewer = "Eddie Lake" },
    .{ .id = 29, .header = "Budget Breakdown",                                .section_type = "Financial",         .status = .in_process, .target = "13", .limit = "16", .reviewer = "Jamik Tashpulatov" },
    .{ .id = 30, .header = "Market Analysis",                                 .section_type = "Research",          .status = .done,       .target = "29", .limit = "32", .reviewer = "Sophia Martinez" },
    .{ .id = 31, .header = "Competitor Comparison",                           .section_type = "Research",          .status = .in_process, .target = "21", .limit = "19", .reviewer = "Assign reviewer" },
    .{ .id = 32, .header = "Maintenance Plan",                                .section_type = "Technical content", .status = .done,       .target = "16", .limit = "23", .reviewer = "Alex Thompson" },
    .{ .id = 33, .header = "User Personas",                                   .section_type = "Research",          .status = .in_process, .target = "27", .limit = "24", .reviewer = "Nina Patel" },
    .{ .id = 34, .header = "Accessibility Compliance",                        .section_type = "Legal",             .status = .done,       .target = "18", .limit = "21", .reviewer = "Assign reviewer" },
    .{ .id = 35, .header = "Performance Metrics",                             .section_type = "Technical content", .status = .in_process, .target = "23", .limit = "26", .reviewer = "David Kim" },
    .{ .id = 36, .header = "Disaster Recovery Plan",                          .section_type = "Technical content", .status = .done,       .target = "14", .limit = "17", .reviewer = "Jamik Tashpulatov" },
    .{ .id = 37, .header = "Third-party Integrations",                        .section_type = "Technical content", .status = .in_process, .target = "25", .limit = "28", .reviewer = "Eddie Lake" },
    .{ .id = 38, .header = "User Feedback Summary",                           .section_type = "Research",          .status = .done,       .target = "20", .limit = "15", .reviewer = "Assign reviewer" },
    .{ .id = 39, .header = "Localization Strategy",                           .section_type = "Narrative",         .status = .in_process, .target = "12", .limit = "19", .reviewer = "Maria Garcia" },
    .{ .id = 40, .header = "Mobile Compatibility",                            .section_type = "Technical content", .status = .done,       .target = "28", .limit = "31", .reviewer = "James Wilson" },
    .{ .id = 41, .header = "Data Migration Plan",                             .section_type = "Technical content", .status = .in_process, .target = "19", .limit = "22", .reviewer = "Assign reviewer" },
    .{ .id = 42, .header = "Quality Assurance Protocols",                     .section_type = "Technical content", .status = .done,       .target = "30", .limit = "33", .reviewer = "Priya Singh" },
    .{ .id = 43, .header = "Stakeholder Analysis",                            .section_type = "Research",          .status = .in_process, .target = "11", .limit = "14", .reviewer = "Eddie Lake" },
    .{ .id = 44, .header = "Environmental Impact Assessment",                 .section_type = "Research",          .status = .done,       .target = "24", .limit = "27", .reviewer = "Assign reviewer" },
    .{ .id = 45, .header = "Intellectual Property Rights",                    .section_type = "Legal",             .status = .in_process, .target = "17", .limit = "20", .reviewer = "Sarah Johnson" },
    .{ .id = 46, .header = "Customer Support Framework",                      .section_type = "Narrative",         .status = .done,       .target = "22", .limit = "25", .reviewer = "Jamik Tashpulatov" },
    .{ .id = 47, .header = "Version Control Strategy",                        .section_type = "Technical content", .status = .in_process, .target = "15", .limit = "18", .reviewer = "Assign reviewer" },
    .{ .id = 48, .header = "Continuous Integration Pipeline",                 .section_type = "Technical content", .status = .done,       .target = "26", .limit = "29", .reviewer = "Michael Chen" },
    .{ .id = 49, .header = "Regulatory Compliance",                           .section_type = "Legal",             .status = .in_process, .target = "13", .limit = "16", .reviewer = "Assign reviewer" },
    .{ .id = 50, .header = "User Authentication System",                      .section_type = "Technical content", .status = .done,       .target = "28", .limit = "31", .reviewer = "Eddie Lake" },
    .{ .id = 51, .header = "Data Analytics Framework",                        .section_type = "Technical content", .status = .in_process, .target = "21", .limit = "24", .reviewer = "Jamik Tashpulatov" },
    .{ .id = 52, .header = "Cloud Infrastructure",                            .section_type = "Technical content", .status = .done,       .target = "16", .limit = "19", .reviewer = "Assign reviewer" },
    .{ .id = 53, .header = "Network Security Measures",                       .section_type = "Technical content", .status = .in_process, .target = "29", .limit = "32", .reviewer = "Lisa Wong" },
    .{ .id = 54, .header = "Project Timeline",                                .section_type = "Planning",          .status = .done,       .target = "14", .limit = "17", .reviewer = "Eddie Lake" },
    .{ .id = 55, .header = "Resource Allocation",                             .section_type = "Planning",          .status = .in_process, .target = "27", .limit = "30", .reviewer = "Assign reviewer" },
    .{ .id = 56, .header = "Team Structure and Roles",                        .section_type = "Planning",          .status = .done,       .target = "20", .limit = "23", .reviewer = "Jamik Tashpulatov" },
    .{ .id = 57, .header = "Communication Protocols",                         .section_type = "Planning",          .status = .in_process, .target = "15", .limit = "18", .reviewer = "Assign reviewer" },
    .{ .id = 58, .header = "Success Metrics",                                 .section_type = "Planning",          .status = .done,       .target = "30", .limit = "33", .reviewer = "Eddie Lake" },
    .{ .id = 59, .header = "Internationalization Support",                    .section_type = "Technical content", .status = .in_process, .target = "23", .limit = "26", .reviewer = "Jamik Tashpulatov" },
    .{ .id = 60, .header = "Backup and Recovery Procedures",                  .section_type = "Technical content", .status = .done,       .target = "18", .limit = "21", .reviewer = "Assign reviewer" },
    .{ .id = 61, .header = "Monitoring and Alerting System",                  .section_type = "Technical content", .status = .in_process, .target = "25", .limit = "28", .reviewer = "Daniel Park" },
    .{ .id = 62, .header = "Code Review Guidelines",                          .section_type = "Technical content", .status = .done,       .target = "12", .limit = "15", .reviewer = "Eddie Lake" },
    .{ .id = 63, .header = "Documentation Standards",                         .section_type = "Technical content", .status = .in_process, .target = "27", .limit = "30", .reviewer = "Jamik Tashpulatov" },
    .{ .id = 64, .header = "Release Management Process",                      .section_type = "Planning",          .status = .done,       .target = "22", .limit = "25", .reviewer = "Assign reviewer" },
    .{ .id = 65, .header = "Feature Prioritization Matrix",                   .section_type = "Planning",          .status = .in_process, .target = "19", .limit = "22", .reviewer = "Emma Davis" },
    .{ .id = 66, .header = "Technical Debt Assessment",                       .section_type = "Technical content", .status = .done,       .target = "24", .limit = "27", .reviewer = "Eddie Lake" },
    .{ .id = 67, .header = "Capacity Planning",                               .section_type = "Planning",          .status = .in_process, .target = "21", .limit = "24", .reviewer = "Jamik Tashpulatov" },
    .{ .id = 68, .header = "Service Level Agreements",                        .section_type = "Legal",             .status = .done,       .target = "26", .limit = "29", .reviewer = "Assign reviewer" },
};

pub const Metric = struct {
    title: []const u8,
    delta: []const u8,
    up: bool,
    value: []const u8,
    foot: []const u8,
    foot_up: bool,
    sub: []const u8,
};

pub const METRICS = [_]Metric{
    .{ .title = "Total Revenue", .delta = "+12.5%", .up = true, .value = "$1,250.00", .foot = "Trending up this month", .foot_up = true, .sub = "Visitors for the last 6 months" },
    .{ .title = "New Customers", .delta = "-20%", .up = false, .value = "1,234", .foot = "Down 20% this period", .foot_up = false, .sub = "Acquisition needs attention" },
    .{ .title = "Active Accounts", .delta = "+12.5%", .up = true, .value = "45,678", .foot = "Strong user retention", .foot_up = true, .sub = "Engagement exceed targets" },
    .{ .title = "Growth Rate", .delta = "+4.5%", .up = true, .value = "4.5%", .foot = "Steady performance increase", .foot_up = true, .sub = "Meets growth projections" },
};
