#!/usr/bin/env python3
"""Convert skrifa's generated autohint styles into Zig data.

Input (pinned cargo registry copy):
  skrifa-0.44.0/generated/generated_autohint_styles.rs
Output:
  src/glifo/autohint/styles_data.zig

The Rust file is itself generated by skrifa's
`scripts/gen_autohint_styles.py`; this converter only transcribes it so the
Zig port never hand-copies script/style tables. Run from the vellz package
root:

  python3 tools/convert_autohint_styles.py [path-to-generated_autohint_styles.rs]
"""

import re
import sys
from pathlib import Path

DEFAULT_SRC = (
    Path.home()
    / ".cargo/registry/src/index.crates.io-1949cf8c6b5b557f/skrifa-0.44.0"
    / "generated/generated_autohint_styles.rs"
)
OUT = Path(__file__).resolve().parent.parent / "src/glifo/autohint/styles_data.zig"

GROUP = {"Default": 0, "Cjk": 1, "Indic": 2}

SCRIPT_RE = re.compile(
    r"ScriptClass \{\s*"
    r'name: "(?P<name>[^"]*)",\s*'
    r"group: ScriptGroup::(?P<group>\w+),\s*"
    r'tag: Tag::new\(b"(?P<tag>[^"]*)"\),\s*'
    r"hint_top_to_bottom: (?P<top>true|false),\s*"
    r'std_chars: "(?P<std>[^"]*)",\s*'
    r"blues: &\[(?P<blues>.*?)\],\s*"
    r"\},",
    re.S,
)
BLUE_RE = re.compile(r'\("(?P<chars>[^"]*)",\s*(?P<zones>BlueZones::[A-Z_]+(?:\.union\(BlueZones::[A-Z_]+\))*)\)')
STYLE_RE = re.compile(
    r"StyleClass \{ name: \"(?P<name>[^\"]*)\", index: (?P<index>\d+), "
    r"script: &SCRIPT_CLASSES\[(?P<script>\d+)\], feature: (?P<feature>None|Some\(Tag::new\(b\"([^\"]*)\"\)\))\ \}",
)
RANGE_RE = re.compile(r"(?P<kind>base|non_base)_range\((\d+), (\d+), (\d+)\)")
SCRIPT_CONST_RE = re.compile(r"pub const (\w+): usize = (\d+);")


def zig_str(text: str) -> str:
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ord(ch) < 0x20:
            out.append(f"\\x{ord(ch):02x}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def tag_bytes(tag: str) -> str:
    b = tag.encode("utf-8")
    assert len(b) == 4, tag
    return ".{ " + ", ".join(f"0x{c:02x}" for c in b) + " }"


def zones_expr(expr: str) -> int:
    # BlueZones::X.union(BlueZones::Y)... -> bit mask
    BITS = {
        "NONE": 0,
        "TOP": 1 << 1,
        "SUB_TOP": 1 << 2,
        "NEUTRAL": 1 << 3,
        "ADJUSTMENT": 1 << 4,
        "X_HEIGHT": 1 << 5,
        "LONG": 1 << 6,
        "HORIZONTAL": 1 << 2,
        "RIGHT": 1 << 1,
    }
    value = 0
    for name in re.findall(r"BlueZones::([A-Z_]+)", expr):
        value |= BITS[name]
    return value


def main() -> None:
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SRC
    text = src.read_text(encoding="utf-8")

    scripts = list(SCRIPT_RE.finditer(text))
    styles = list(STYLE_RE.finditer(text))
    ranges = list(RANGE_RE.finditer(text))
    assert len(scripts) == 61, len(scripts)
    assert len(styles) == 91, len(styles)
    assert len(ranges) > 300, len(ranges)

    lines = []
    lines.append("//! Generated autohint script/style tables (do not edit).")
    lines.append("//!")
    lines.append("//! Transcribed from `skrifa-0.44.0/generated/generated_autohint_styles.rs`")
    lines.append("//! by `tools/convert_autohint_styles.py`. Raw indices/bit masks only;")
    lines.append("//! `styles.zig` maps them onto typed values.")
    lines.append("")
    lines.append('const bz = @import("blue_zones.zig");')
    lines.append("")
    lines.append("pub const RawBlue = bz.BluePair;")
    lines.append("")
    lines.append("pub const RawScript = struct {")
    lines.append("    name: []const u8,")
    lines.append("    /// 0 = Default, 1 = Cjk, 2 = Indic (`ScriptGroup`).")
    lines.append("    group: u8,")
    lines.append("    tag: [4]u8,")
    lines.append("    hint_top_to_bottom: bool,")
    lines.append("    std_chars: []const u8,")
    lines.append("    blues: []const RawBlue,")
    lines.append("};")
    lines.append("")
    lines.append("pub const RawStyle = struct {")
    lines.append("    name: []const u8,")
    lines.append("    script: u16,")
    lines.append("    feature: ?[4]u8,")
    lines.append("};")
    lines.append("")
    lines.append("pub const RawRange = struct {")
    lines.append("    first: u32,")
    lines.append("    last: u32,")
    lines.append("    style: u16,")
    lines.append("    non_base: bool,")
    lines.append("};")
    lines.append("")

    lines.append("pub const SCRIPT_CLASSES = [_]RawScript{")
    for m in scripts:
        blues = m.group("blues")
        blue_items = []
        for bm in BLUE_RE.finditer(blues):
            blue_items.append(
                f'    .{{ .chars = {zig_str(bm.group("chars"))}, .zones = .{{ .bits = {zones_expr(bm.group("zones"))} }} }},'
            )
        lines.append(f"    .{{")
        lines.append(f"        .name = {zig_str(m.group('name'))},")
        lines.append(f"        .group = {GROUP[m.group('group')]},")
        lines.append(f"        .tag = {tag_bytes(m.group('tag'))},")
        lines.append(
            f"        .hint_top_to_bottom = {'true' if m.group('top') == 'true' else 'false'},"
        )
        lines.append(f"        .std_chars = {zig_str(m.group('std'))},")
        lines.append("        .blues = &.{")
        lines.extend(blue_items)
        lines.append("        },")
        lines.append("    },")
    lines.append("};")
    lines.append("")

    lines.append("pub const STYLE_CLASSES = [_]RawStyle{")
    for m in styles:
        feature = m.group("feature")
        if feature == "None":
            feat = "null"
        else:
            tag = re.search(r'b"([^"]*)"', feature).group(1)
            feat = tag_bytes(tag)
        lines.append("    .{")
        lines.append(f"        .name = {zig_str(m.group('name'))},")
        lines.append(f"        .script = {m.group('script')},")
        lines.append(f"        .feature = {feat},")
        lines.append("    },")
    lines.append("};")
    lines.append("")

    lines.append("pub const STYLE_RANGES = [_]RawRange{")
    for m in ranges:
        non_base = "true" if m.group("kind") == "non_base" else "false"
        lines.append(
            f"    .{{ .first = {m.group(2)}, .last = {m.group(3)}, "
            f".style = {m.group(4)}, .non_base = {non_base} }},"
        )
    lines.append("};")
    lines.append("")

    # Index constants for ported tests. The two impl blocks use the same
    # names; keep script indices under `script` and style indices under
    # `style`.
    script_block = text[text.index("impl ScriptClass {") : text.index("pub const STYLE_CLASSES")]
    style_block = text[text.index("impl StyleClass {"):]
    lines.append("pub const script_index = struct {")
    for m in SCRIPT_CONST_RE.finditer(script_block):
        lines.append(f"    pub const {m.group(1).lower()} : usize = {m.group(2)};")
    lines.append("};")
    lines.append("")
    lines.append("pub const style_index = struct {")
    for m in SCRIPT_CONST_RE.finditer(style_block):
        lines.append(f"    pub const {m.group(1).lower()} : usize = {m.group(2)};")
    lines.append("};")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(scripts)} scripts, {len(styles)} styles, {len(ranges)} ranges)")


if __name__ == "__main__":
    main()
