//! Parser for the shared scene corpus format (version 1).
//!
//! The same files under `tests/scenes/` drive the upstream Rust oracle
//! (`tools/oracle-rs`) and vellz, so scene construction cannot drift between
//! the two implementations. See `tools/oracle-rs/README.md` for the schema.
//!
//! The M3 `glyph_run` command (`font`/`font_size`/`hint`/`glyph_transform`/
//! `embolden`/`normalized_coords`/`atlas_cache`/`style`/`glyphs`) carries an
//! explicitly positioned glyph list; the scenes are generated by
//! `tools/gen_glyph_scenes.py`. Decoration and the deferred glyph properties
//! are parsed so a scene can never silently drop them; `embolden` is
//! implemented in both backends and `normalized_coords` stays deferred.
//!
//! Ownership: `parse` copies everything it needs into an arena that the caller
//! provides via `Parsed`. The returned slices point into that arena and are
//! valid until `deinit`.

const std = @import("std");

pub const Affine = [6]f64;

pub const Settings = struct {
    /// "quality" (f32 pipeline) or "speed" (u8 pipeline).
    mode: enum { quality, speed } = .quality,
    /// Additional renderer threads.
    threads: u16 = 0,
    /// "fallback" or "native" SIMD level.
    level: enum { fallback, native } = .fallback,
};

pub const TargetInit = enum { clear, src_over };

pub const Join = enum { miter, round, bevel };
pub const Cap = enum { butt, round, square };

pub const Extend = enum { pad, repeat, reflect };
pub const ImageQuality = enum { low, medium, high };
pub const ImageFormat = enum { rgba8, bgra8 };
pub const ImageAlphaType = enum { alpha, premultiplied };
pub const MaskKind = enum { alpha, luminance };

/// Filter edge handling for out-of-bounds sampling.
pub const EdgeMode = enum { duplicate, wrap, mirror, none };

pub const DropShadowSpec = struct {
    dx: f64,
    dy: f64,
    std_deviation: f64,
    rgba8: [4]u8,
    edge_mode: EdgeMode,
};

/// One variant of [`FilterSpec`]; exactly one key is present in the JSON.
///
/// `vello_common`/`vello_cpu` currently support single-primitive filter graphs
/// only; a scene that needs a compound effect uses `drop_shadow` /
/// `drop_shadow_only`.
pub const FilterSpec = union(enum) {
    flood: [4]u8,
    gaussian_blur: struct {
        std_deviation: f64,
        edge_mode: EdgeMode,
    },
    offset: struct {
        dx: f64,
        dy: f64,
    },
    drop_shadow: DropShadowSpec,
    drop_shadow_only: DropShadowSpec,
};

/// A `push_layer` with a filter plus the optional regular layer properties.
pub const FilterLayerSpec = struct {
    filter: FilterSpec,
    clip: ?[]const u8 = null,
    blend: ?BlendSpec = null,
    opacity: ?f64 = null,
    mask: ?MaskSpec = null,
};

/// peniko's `Mix` compositing functions.
pub const Mix = enum {
    normal,
    multiply,
    screen,
    overlay,
    darken,
    lighten,
    color_dodge,
    color_burn,
    hard_light,
    soft_light,
    difference,
    exclusion,
    hue,
    saturation,
    color,
    luminosity,
};

/// peniko's `Compose` layer composition functions.
pub const Compose = enum {
    clear,
    copy,
    dest,
    src_over,
    dest_over,
    src_in,
    dest_in,
    src_out,
    dest_out,
    src_atop,
    dest_atop,
    xor,
    plus,
    plus_lighter,
};

pub const BlendSpec = struct {
    mix: Mix,
    compose: Compose,
};

pub const ColorStop = struct {
    offset: f64,
    rgba8: [4]u8,
};

/// One variant of [`GradientSpec`]; exactly one key is present in the JSON.
pub const GradientKind = union(enum) {
    linear: struct {
        start: [2]f64,
        end: [2]f64,
    },
    radial: struct {
        start_center: [2]f64,
        start_radius: f64,
        end_center: [2]f64,
        end_radius: f64,
    },
    sweep: struct {
        center: [2]f64,
        start_angle: f64,
        end_angle: f64,
    },
};

pub const GradientSpec = struct {
    kind: GradientKind,
    stops: []const ColorStop,
    extend: Extend,
};

pub const ImageSamplerSpec = struct {
    x_extend: Extend,
    y_extend: Extend,
    quality: ImageQuality,
    alpha: f64,
};

pub const ImageSpec = struct {
    /// Asset path relative to the scene file's directory; arena-owned.
    asset: []const u8,
    width: u16,
    height: u16,
    format: ImageFormat,
    alpha_type: ImageAlphaType,
    sampler: ImageSamplerSpec,
};

pub const MaskSpec = struct {
    /// Asset path relative to the scene file's directory; arena-owned.
    asset: []const u8,
    width: u16,
    height: u16,
    format: ImageFormat,
    alpha_type: ImageAlphaType,
    kind: MaskKind,
};

pub const PaintSpec = union(enum) {
    solid: [4]u8,
    gradient: GradientSpec,
    image: ImageSpec,
};

pub const LayerSpec = union(enum) {
    clip: []const u8,
    blend: BlendSpec,
    opacity: f64,
    mask: MaskSpec,
    filter: FilterLayerSpec,
};

pub const StrokeSpec = struct {
    width: f64,
    join: ?Join = null,
    start_cap: ?Cap = null,
    end_cap: ?Cap = null,
    miter_limit: ?f64 = null,
    dash: ?[]const f64 = null,
    dash_offset: f64 = 0,
};

pub const BlurredRoundedRectSpec = struct {
    rect: [4]f64,
    radius: f64,
    std_dev: f64,
    invert: bool = false,
};

/// Font asset for a positioned glyph run.
pub const FontSpec = struct {
    /// Asset path relative to the scene file's directory; arena-owned.
    asset: []const u8,
    index: u32 = 0,
};

/// One positioned glyph: font glyph id plus run-space position.
pub const PositionedGlyphSpec = struct {
    id: u32,
    x: f32,
    y: f32,
};

/// Decoration placement (T5). Parsed so an unsupported scene fails loudly
/// instead of silently dropping the decoration.
pub const DecorationSpec = struct {
    x_range: [2]f32,
    baseline_y: f32,
    offset: f32,
    size: f32,
    buffer: f32,
};

/// Style of a glyph run.
pub const GlyphStyle = enum { fill, stroke };

/// A positioned glyph run drawn through the `glifo` stack.
pub const GlyphRunSpec = struct {
    font: FontSpec,
    font_size: f32,
    hint: bool = true,
    /// Per-glyph transform (e.g. skew for fake italics).
    glyph_transform: ?Affine = null,
    /// Synthetic embolden amount (x, y); forwarded as `FontEmbolden`.
    embolden: ?[2]f32 = null,
    /// Normalized variation coordinates in `[-1, 1]`, converted at the run
    /// boundary with `F2Dot14::from_f32` (`glifo.f2dot14FromF32`).
    normalized_coords: ?[]const f32 = null,
    atlas_cache: bool = false,
    style: GlyphStyle = .fill,
    glyphs: []const PositionedGlyphSpec,
    decoration: ?DecorationSpec = null,
};

pub const Command = union(enum) {
    set_transform: Affine,
    reset_transform,
    set_paint_transform: Affine,
    reset_paint_transform,
    set_paint: PaintSpec,
    set_fill_rule: enum { nonzero, evenodd },
    set_stroke: StrokeSpec,
    set_aliasing_threshold: ?u8,
    fill_rect: [4]f64,
    stroke_rect: [4]f64,
    fill_blurred_rounded_rect: BlurredRoundedRectSpec,
    fill_path: []const u8,
    stroke_path: []const u8,
    push_clip_path: []const u8,
    pop_clip_path,
    push_clip_layer: []const u8,
    push_layer: LayerSpec,
    pop_layer,
    set_filter_effect: FilterSpec,
    reset_filter_effect,
    glyph_run: GlyphRunSpec,
    reset,
};

pub const Scene = struct {
    version: u32 = 1,
    width: u16,
    height: u16,
    settings: Settings = .{},
    target_init: TargetInit = .clear,
    commands: []const Command,
};

pub const Parsed = struct {
    arena: std.heap.ArenaAllocator,
    scene: Scene,

    pub fn deinit(self: *Parsed) void {
        self.arena.deinit();
    }
};

pub const ParseError = error{InvalidScene} || std.mem.Allocator.Error;

/// Parses scene JSON. The result owns an arena; call `deinit` when done.
pub fn parse(backing: std.mem.Allocator, text: []const u8) ParseError!Parsed {
    var arena = std.heap.ArenaAllocator.init(backing);
    errdefer arena.deinit();
    const alloc = arena.allocator();

    const root = std.json.parseFromSliceLeaky(std.json.Value, alloc, text, .{}) catch {
        return error.InvalidScene;
    };
    const obj = switch (root) {
        .object => |o| o,
        else => return error.InvalidScene,
    };

    var scene: Scene = .{
        .width = try u16Field(obj, "width"),
        .height = try u16Field(obj, "height"),
        .commands = &.{},
    };

    if (obj.get("version")) |v| {
        scene.version = switch (v) {
            .integer => |i| std.math.cast(u32, i) orelse return error.InvalidScene,
            else => return error.InvalidScene,
        };
    }
    if (scene.version != 1) return error.InvalidScene;

    if (obj.get("settings")) |settings_value| {
        const settings_obj = switch (settings_value) {
            .object => |o| o,
            else => return error.InvalidScene,
        };
        if (settings_obj.get("mode")) |mode| {
            const s = stringOf(mode) orelse return error.InvalidScene;
            scene.settings.mode = if (std.mem.eql(u8, s, "quality"))
                .quality
            else if (std.mem.eql(u8, s, "speed"))
                .speed
            else
                return error.InvalidScene;
        }
        if (settings_obj.get("threads")) |threads| {
            scene.settings.threads = switch (threads) {
                .integer => |i| std.math.cast(u16, i) orelse return error.InvalidScene,
                else => return error.InvalidScene,
            };
        }
        if (settings_obj.get("level")) |level| {
            const s = stringOf(level) orelse return error.InvalidScene;
            scene.settings.level = if (std.mem.eql(u8, s, "fallback"))
                .fallback
            else if (std.mem.eql(u8, s, "native"))
                .native
            else
                return error.InvalidScene;
        }
    }

    if (obj.get("target_init")) |target| {
        const s = stringOf(target) orelse return error.InvalidScene;
        scene.target_init = if (std.mem.eql(u8, s, "clear"))
            .clear
        else if (std.mem.eql(u8, s, "src_over"))
            .src_over
        else
            return error.InvalidScene;
    }

    if (obj.get("commands")) |commands_value| {
        const array = switch (commands_value) {
            .array => |a| a,
            else => return error.InvalidScene,
        };
        const commands = try alloc.alloc(Command, array.items.len);
        for (array.items, 0..) |item, i| {
            commands[i] = try parseCommand(alloc, item);
        }
        scene.commands = commands;
    }

    return .{ .arena = arena, .scene = scene };
}

fn parseCommand(alloc: std.mem.Allocator, value: std.json.Value) ParseError!Command {
    const obj = switch (value) {
        .object => |o| o,
        else => return error.InvalidScene,
    };
    const op = stringOf(obj.get("op") orelse return error.InvalidScene) orelse
        return error.InvalidScene;

    if (std.mem.eql(u8, op, "set_transform")) return .{ .set_transform = try affineField(obj) };
    if (std.mem.eql(u8, op, "reset_transform")) return .reset_transform;
    if (std.mem.eql(u8, op, "set_paint_transform")) return .{ .set_paint_transform = try affineField(obj) };
    if (std.mem.eql(u8, op, "reset_paint_transform")) return .reset_paint_transform;
    if (std.mem.eql(u8, op, "set_paint")) return .{ .set_paint = try parsePaint(alloc, obj) };
    if (std.mem.eql(u8, op, "set_fill_rule")) {
        const s = stringOf(obj.get("rule") orelse return error.InvalidScene) orelse
            return error.InvalidScene;
        if (std.mem.eql(u8, s, "nonzero")) return .{ .set_fill_rule = .nonzero };
        if (std.mem.eql(u8, s, "evenodd")) return .{ .set_fill_rule = .evenodd };
        return error.InvalidScene;
    }
    if (std.mem.eql(u8, op, "set_stroke")) return .{ .set_stroke = try parseStroke(alloc, obj) };
    if (std.mem.eql(u8, op, "set_aliasing_threshold")) {
        const threshold: ?u8 = switch (obj.get("value") orelse .null) {
            .null => null,
            .integer => |i| std.math.cast(u8, i) orelse return error.InvalidScene,
            else => return error.InvalidScene,
        };
        return .{ .set_aliasing_threshold = threshold };
    }
    if (std.mem.eql(u8, op, "fill_rect")) return .{ .fill_rect = try rectField(obj) };
    if (std.mem.eql(u8, op, "stroke_rect")) return .{ .stroke_rect = try rectField(obj) };
    if (std.mem.eql(u8, op, "fill_blurred_rounded_rect")) {
        return .{ .fill_blurred_rounded_rect = .{
            .rect = try rectField(obj),
            .radius = try floatField(obj, "radius"),
            .std_dev = try floatField(obj, "std_dev"),
            .invert = if (obj.get("invert")) |invert_value| switch (invert_value) {
                .bool => |b| b,
                else => return error.InvalidScene,
            } else false,
        } };
    }
    if (std.mem.eql(u8, op, "fill_path")) return .{ .fill_path = try pathField(alloc, obj) };
    if (std.mem.eql(u8, op, "stroke_path")) return .{ .stroke_path = try pathField(alloc, obj) };
    if (std.mem.eql(u8, op, "push_clip_path")) return .{ .push_clip_path = try pathField(alloc, obj) };
    if (std.mem.eql(u8, op, "pop_clip_path")) return .pop_clip_path;
    if (std.mem.eql(u8, op, "push_clip_layer")) return .{ .push_clip_layer = try pathField(alloc, obj) };
    if (std.mem.eql(u8, op, "push_layer")) return .{ .push_layer = try parseLayer(alloc, obj) };
    if (std.mem.eql(u8, op, "pop_layer")) return .pop_layer;
    if (std.mem.eql(u8, op, "glyph_run")) return .{ .glyph_run = try parseGlyphRun(alloc, obj) };
    if (std.mem.eql(u8, op, "set_filter_effect")) {
        return .{ .set_filter_effect = try parseFilter(obj.get("filter") orelse return error.InvalidScene) };
    }
    if (std.mem.eql(u8, op, "reset_filter_effect")) return .reset_filter_effect;
    if (std.mem.eql(u8, op, "reset")) return .reset;
    return error.InvalidScene;
}

fn parsePaint(alloc: std.mem.Allocator, obj: std.json.ObjectMap) ParseError!PaintSpec {
    const variants = @as(u8, @intFromBool(obj.get("rgba8") != null)) +
        @intFromBool(obj.get("gradient") != null) +
        @intFromBool(obj.get("image") != null);
    if (variants != 1) return error.InvalidScene;
    if (obj.get("rgba8") != null) return .{ .solid = try rgba8Field(obj) };
    if (obj.get("gradient")) |value| return .{ .gradient = try parseGradient(alloc, value) };
    return .{ .image = try parseImage(alloc, obj.get("image").?) };
}

fn parseGradient(alloc: std.mem.Allocator, value: std.json.Value) ParseError!GradientSpec {
    const obj = try objectOf(value);
    const stops_value = obj.get("stops") orelse return error.InvalidScene;
    const stops_array = switch (stops_value) {
        .array => |a| a,
        else => return error.InvalidScene,
    };
    const stops = try alloc.alloc(ColorStop, stops_array.items.len);
    for (stops_array.items, 0..) |item, i| {
        stops[i] = try parseColorStop(item);
    }
    return .{
        .kind = try parseGradientKind(obj.get("kind") orelse return error.InvalidScene),
        .stops = stops,
        .extend = try enumField(Extend, obj, "extend"),
    };
}

fn parseGradientKind(value: std.json.Value) ParseError!GradientKind {
    const obj = try objectOf(value);
    if (obj.count() != 1) return error.InvalidScene;
    if (obj.get("linear")) |inner| {
        const inner_obj = try objectOf(inner);
        return .{ .linear = .{
            .start = try pointField(inner_obj, "start"),
            .end = try pointField(inner_obj, "end"),
        } };
    }
    if (obj.get("radial")) |inner| {
        const inner_obj = try objectOf(inner);
        return .{ .radial = .{
            .start_center = try pointField(inner_obj, "start_center"),
            .start_radius = try floatField(inner_obj, "start_radius"),
            .end_center = try pointField(inner_obj, "end_center"),
            .end_radius = try floatField(inner_obj, "end_radius"),
        } };
    }
    if (obj.get("sweep")) |inner| {
        const inner_obj = try objectOf(inner);
        return .{ .sweep = .{
            .center = try pointField(inner_obj, "center"),
            .start_angle = try floatField(inner_obj, "start_angle"),
            .end_angle = try floatField(inner_obj, "end_angle"),
        } };
    }
    return error.InvalidScene;
}

fn parseColorStop(value: std.json.Value) ParseError!ColorStop {
    const obj = try objectOf(value);
    return .{
        .offset = try floatField(obj, "offset"),
        .rgba8 = try rgba8Field(obj),
    };
}

fn parseImage(alloc: std.mem.Allocator, value: std.json.Value) ParseError!ImageSpec {
    const obj = try objectOf(value);
    const sampler_obj = try objectOf(obj.get("sampler") orelse return error.InvalidScene);
    return .{
        .asset = try dupeField(alloc, obj, "asset"),
        .width = try u16Field(obj, "width"),
        .height = try u16Field(obj, "height"),
        .format = try enumField(ImageFormat, obj, "format"),
        .alpha_type = try enumField(ImageAlphaType, obj, "alpha_type"),
        .sampler = .{
            .x_extend = try enumField(Extend, sampler_obj, "x_extend"),
            .y_extend = try enumField(Extend, sampler_obj, "y_extend"),
            .quality = try enumField(ImageQuality, sampler_obj, "quality"),
            .alpha = try floatField(sampler_obj, "alpha"),
        },
    };
}

fn parseMask(alloc: std.mem.Allocator, obj: std.json.ObjectMap) ParseError!MaskSpec {
    return .{
        .asset = try dupeField(alloc, obj, "asset"),
        .width = try u16Field(obj, "width"),
        .height = try u16Field(obj, "height"),
        .format = try enumField(ImageFormat, obj, "format"),
        .alpha_type = try enumField(ImageAlphaType, obj, "alpha_type"),
        .kind = try enumField(MaskKind, obj, "kind"),
    };
}

fn parseLayer(alloc: std.mem.Allocator, obj: std.json.ObjectMap) ParseError!LayerSpec {
    const kind = stringOf(obj.get("kind") orelse return error.InvalidScene) orelse
        return error.InvalidScene;
    if (std.mem.eql(u8, kind, "clip")) {
        return .{ .clip = try pathField(alloc, obj) };
    }
    if (std.mem.eql(u8, kind, "blend")) {
        const blend_obj = try objectOf(obj.get("blend") orelse return error.InvalidScene);
        return .{ .blend = .{
            .mix = try enumField(Mix, blend_obj, "mix"),
            .compose = try enumField(Compose, blend_obj, "compose"),
        } };
    }
    if (std.mem.eql(u8, kind, "opacity")) {
        return .{ .opacity = try floatField(obj, "opacity") };
    }
    if (std.mem.eql(u8, kind, "mask")) {
        const mask_obj = try objectOf(obj.get("mask") orelse return error.InvalidScene);
        return .{ .mask = try parseMask(alloc, mask_obj) };
    }
    if (std.mem.eql(u8, kind, "filter")) {
        var spec: FilterLayerSpec = .{
            .filter = try parseFilter(obj.get("filter") orelse return error.InvalidScene),
        };
        if (obj.get("clip")) |v| {
            const s = stringOf(v) orelse return error.InvalidScene;
            spec.clip = alloc.dupe(u8, s) catch return error.OutOfMemory;
        }
        if (obj.get("blend")) |v| {
            const blend_obj = try objectOf(v);
            spec.blend = .{
                .mix = try enumField(Mix, blend_obj, "mix"),
                .compose = try enumField(Compose, blend_obj, "compose"),
            };
        }
        if (obj.get("opacity")) |v| {
            spec.opacity = switch (v) {
                .float => |f| f,
                .integer => |i| @floatFromInt(i),
                else => return error.InvalidScene,
            };
        }
        if (obj.get("mask")) |v| {
            const mask_obj = try objectOf(v);
            spec.mask = try parseMask(alloc, mask_obj);
        }
        return .{ .filter = spec };
    }
    return error.InvalidScene;
}

/// Parses a filter primitive. Exactly one of the `kind` variants is expected.
fn parseFilter(value: std.json.Value) ParseError!FilterSpec {
    const obj = try objectOf(value);
    const kind = stringOf(obj.get("kind") orelse return error.InvalidScene) orelse
        return error.InvalidScene;

    if (std.mem.eql(u8, kind, "flood")) {
        return .{ .flood = try rgba8Field(obj) };
    }
    if (std.mem.eql(u8, kind, "gaussian_blur")) {
        return .{ .gaussian_blur = .{
            .std_deviation = try floatField(obj, "std_deviation"),
            .edge_mode = try enumField(EdgeMode, obj, "edge_mode"),
        } };
    }
    if (std.mem.eql(u8, kind, "offset")) {
        return .{ .offset = .{
            .dx = try floatField(obj, "dx"),
            .dy = try floatField(obj, "dy"),
        } };
    }
    if (std.mem.eql(u8, kind, "drop_shadow") or std.mem.eql(u8, kind, "drop_shadow_only")) {
        const shadow = DropShadowSpec{
            .dx = try floatField(obj, "dx"),
            .dy = try floatField(obj, "dy"),
            .std_deviation = try floatField(obj, "std_deviation"),
            .rgba8 = try rgba8Field(obj),
            .edge_mode = try enumField(EdgeMode, obj, "edge_mode"),
        };
        return if (std.mem.eql(u8, kind, "drop_shadow"))
            .{ .drop_shadow = shadow }
        else
            .{ .drop_shadow_only = shadow };
    }
    return error.InvalidScene;
}

fn parseStroke(alloc: std.mem.Allocator, obj: std.json.ObjectMap) ParseError!StrokeSpec {
    var spec: StrokeSpec = .{ .width = try floatField(obj, "width") };
    if (obj.get("join")) |v| {
        const s = stringOf(v) orelse return error.InvalidScene;
        spec.join = if (std.mem.eql(u8, s, "miter"))
            .miter
        else if (std.mem.eql(u8, s, "round"))
            .round
        else if (std.mem.eql(u8, s, "bevel"))
            .bevel
        else
            return error.InvalidScene;
    }
    if (obj.get("start_cap")) |v| spec.start_cap = try parseCap(v);
    if (obj.get("end_cap")) |v| spec.end_cap = try parseCap(v);
    if (obj.get("miter_limit")) |v| {
        spec.miter_limit = switch (v) {
            .float => |f| f,
            .integer => |i| @floatFromInt(i),
            else => return error.InvalidScene,
        };
    }
    if (obj.get("dash_offset")) |v| {
        spec.dash_offset = switch (v) {
            .float => |f| f,
            .integer => |i| @floatFromInt(i),
            else => return error.InvalidScene,
        };
    }
    if (obj.get("dash")) |v| {
        const array = switch (v) {
            .array => |a| a,
            else => return error.InvalidScene,
        };
        const dash = try alloc.alloc(f64, array.items.len);
        for (array.items, 0..) |item, i| {
            dash[i] = switch (item) {
                .float => |f| f,
                .integer => |n| @floatFromInt(n),
                else => return error.InvalidScene,
            };
        }
        spec.dash = dash;
    }
    return spec;
}

fn parseCap(value: std.json.Value) ParseError!Cap {
    const s = stringOf(value) orelse return error.InvalidScene;
    if (std.mem.eql(u8, s, "butt")) return .butt;
    if (std.mem.eql(u8, s, "round")) return .round;
    if (std.mem.eql(u8, s, "square")) return .square;
    return error.InvalidScene;
}

/// Parses a `glyph_run` command: an explicitly positioned glyph list plus the
/// run properties the `glifo` stack consumes.
fn parseGlyphRun(alloc: std.mem.Allocator, obj: std.json.ObjectMap) ParseError!GlyphRunSpec {
    const font_obj = try objectOf(obj.get("font") orelse return error.InvalidScene);
    var spec: GlyphRunSpec = .{
        .font = .{
            .asset = try dupeField(alloc, font_obj, "asset"),
            .index = if (font_obj.get("index")) |value| switch (value) {
                .integer => |i| std.math.cast(u32, i) orelse return error.InvalidScene,
                else => return error.InvalidScene,
            } else 0,
        },
        .font_size = try f32Field(obj, "font_size"),
        .glyphs = undefined,
    };

    const glyphs_value = obj.get("glyphs") orelse return error.InvalidScene;
    const glyphs_array = switch (glyphs_value) {
        .array => |a| a,
        else => return error.InvalidScene,
    };
    const glyphs = try alloc.alloc(PositionedGlyphSpec, glyphs_array.items.len);
    for (glyphs_array.items, 0..) |item, i| {
        const glyph_obj = try objectOf(item);
        glyphs[i] = .{
            .id = try u32Field(glyph_obj, "id"),
            .x = try f32Field(glyph_obj, "x"),
            .y = try f32Field(glyph_obj, "y"),
        };
    }
    spec.glyphs = glyphs;

    if (obj.get("hint")) |value| spec.hint = try boolField(value);
    if (obj.get("atlas_cache")) |value| spec.atlas_cache = try boolField(value);
    if (obj.get("style")) |value| {
        const s = stringOf(value) orelse return error.InvalidScene;
        if (std.mem.eql(u8, s, "fill")) {
            spec.style = .fill;
        } else if (std.mem.eql(u8, s, "stroke")) {
            spec.style = .stroke;
        } else {
            return error.InvalidScene;
        }
    }
    if (obj.get("glyph_transform")) |value| {
        spec.glyph_transform = try affineArrayField(value);
    }
    if (obj.get("embolden")) |value| {
        spec.embolden = try f32ArrayField(value, 2);
    }
    if (obj.get("normalized_coords")) |value| {
        const array = switch (value) {
            .array => |a| a,
            else => return error.InvalidScene,
        };
        const coords = try alloc.alloc(f32, array.items.len);
        for (array.items, 0..) |item, i| {
            coords[i] = @floatCast(try numberAsF64(item));
        }
        spec.normalized_coords = coords;
    }
    if (obj.get("decoration")) |value| {
        const decoration_obj = try objectOf(value);
        const x_range = try f32ArrayField(decoration_obj.get("x_range") orelse return error.InvalidScene, 2);
        spec.decoration = .{
            .x_range = x_range,
            .baseline_y = try f32Field(decoration_obj, "baseline_y"),
            .offset = try f32Field(decoration_obj, "offset"),
            .size = try f32Field(decoration_obj, "size"),
            .buffer = try f32Field(decoration_obj, "buffer"),
        };
    }
    return spec;
}

fn affineArrayField(value: std.json.Value) ParseError!Affine {
    const array = switch (value) {
        .array => |a| a,
        else => return error.InvalidScene,
    };
    if (array.items.len != 6) return error.InvalidScene;
    var out: Affine = undefined;
    for (array.items, 0..) |item, i| {
        out[i] = try numberAsF64(item);
    }
    return out;
}

fn f32ArrayField(value: std.json.Value, comptime len: usize) ParseError![len]f32 {
    const array = switch (value) {
        .array => |a| a,
        else => return error.InvalidScene,
    };
    if (array.items.len != len) return error.InvalidScene;
    var out: [len]f32 = undefined;
    for (array.items, 0..) |item, i| {
        out[i] = @floatCast(try numberAsF64(item));
    }
    return out;
}

fn numberAsF64(value: std.json.Value) ParseError!f64 {
    return switch (value) {
        .float => |f| f,
        .integer => |i| @floatFromInt(i),
        else => error.InvalidScene,
    };
}

fn boolField(value: std.json.Value) ParseError!bool {
    return switch (value) {
        .bool => |b| b,
        else => error.InvalidScene,
    };
}

fn f32Field(obj: std.json.ObjectMap, name: []const u8) ParseError!f32 {
    return @floatCast(try floatField(obj, name));
}

fn u32Field(obj: std.json.ObjectMap, name: []const u8) ParseError!u32 {
    const value = obj.get(name) orelse return error.InvalidScene;
    return switch (value) {
        .integer => |i| std.math.cast(u32, i) orelse error.InvalidScene,
        else => error.InvalidScene,
    };
}

fn affineField(obj: std.json.ObjectMap) ParseError!Affine {
    const array = switch (obj.get("affine") orelse return error.InvalidScene) {
        .array => |a| a,
        else => return error.InvalidScene,
    };
    if (array.items.len != 6) return error.InvalidScene;
    var out: Affine = undefined;
    for (array.items, 0..) |item, i| {
        out[i] = switch (item) {
            .float => |f| f,
            .integer => |n| @floatFromInt(n),
            else => return error.InvalidScene,
        };
    }
    return out;
}

fn rectField(obj: std.json.ObjectMap) ParseError![4]f64 {
    const array = switch (obj.get("rect") orelse return error.InvalidScene) {
        .array => |a| a,
        else => return error.InvalidScene,
    };
    if (array.items.len != 4) return error.InvalidScene;
    var out: [4]f64 = undefined;
    for (array.items, 0..) |item, i| {
        out[i] = switch (item) {
            .float => |f| f,
            .integer => |n| @floatFromInt(n),
            else => return error.InvalidScene,
        };
    }
    return out;
}

fn rgba8Field(obj: std.json.ObjectMap) ParseError![4]u8 {
    const array = switch (obj.get("rgba8") orelse return error.InvalidScene) {
        .array => |a| a,
        else => return error.InvalidScene,
    };
    if (array.items.len != 4) return error.InvalidScene;
    var out: [4]u8 = undefined;
    for (array.items, 0..) |item, i| {
        out[i] = switch (item) {
            .integer => |n| std.math.cast(u8, n) orelse return error.InvalidScene,
            else => return error.InvalidScene,
        };
    }
    return out;
}

fn pathField(alloc: std.mem.Allocator, obj: std.json.ObjectMap) ParseError![]const u8 {
    return dupeField(alloc, obj, "path");
}

fn dupeField(alloc: std.mem.Allocator, obj: std.json.ObjectMap, name: []const u8) ParseError![]const u8 {
    const s = stringOf(obj.get(name) orelse return error.InvalidScene) orelse
        return error.InvalidScene;
    return alloc.dupe(u8, s) catch return error.OutOfMemory;
}

fn objectOf(value: std.json.Value) ParseError!std.json.ObjectMap {
    return switch (value) {
        .object => |o| o,
        else => error.InvalidScene,
    };
}

fn enumField(comptime T: type, obj: std.json.ObjectMap, name: []const u8) ParseError!T {
    const s = stringOf(obj.get(name) orelse return error.InvalidScene) orelse
        return error.InvalidScene;
    return std.meta.stringToEnum(T, s) orelse error.InvalidScene;
}

fn pointField(obj: std.json.ObjectMap, name: []const u8) ParseError![2]f64 {
    const array = switch (obj.get(name) orelse return error.InvalidScene) {
        .array => |a| a,
        else => return error.InvalidScene,
    };
    if (array.items.len != 2) return error.InvalidScene;
    var out: [2]f64 = undefined;
    for (array.items, 0..) |item, i| {
        out[i] = switch (item) {
            .float => |f| f,
            .integer => |n| @floatFromInt(n),
            else => return error.InvalidScene,
        };
    }
    return out;
}

fn stringOf(value: std.json.Value) ?[]const u8 {
    return switch (value) {
        .string => |s| s,
        else => null,
    };
}

fn u16Field(obj: std.json.ObjectMap, name: []const u8) ParseError!u16 {
    const value = obj.get(name) orelse return error.InvalidScene;
    return switch (value) {
        .integer => |i| std.math.cast(u16, i) orelse error.InvalidScene,
        else => error.InvalidScene,
    };
}

fn floatField(obj: std.json.ObjectMap, name: []const u8) ParseError!f64 {
    const value = obj.get(name) orelse return error.InvalidScene;
    return switch (value) {
        .float => |f| f,
        .integer => |i| @floatFromInt(i),
        else => error.InvalidScene,
    };
}

test "parse every corpus scene" {
    const std_testing = std.testing;
    const io = std_testing.io;
    var dir = try std.Io.Dir.cwd().openDir(io, "tests/scenes", .{ .iterate = true });
    defer dir.close(io);

    var count: usize = 0;
    var it = dir.iterate();
    while (try it.next(io)) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.name, ".json")) continue;
        const text = try dir.readFileAlloc(io, entry.name, std_testing.allocator, .unlimited);
        defer std_testing.allocator.free(text);
        var parsed = try parse(std_testing.allocator, text);
        defer parsed.deinit();
        try std_testing.expect(parsed.scene.width > 0);
        try std_testing.expect(parsed.scene.height > 0);
        count += 1;
    }
    try std_testing.expect(count >= 30);
}

test "commands parse with expected variants" {
    const text =
        \\{"version":1,"width":8,"height":8,
        \\ "commands":[
        \\   {"op":"set_paint","rgba8":[1,2,3,4]},
        \\   {"op":"set_stroke","width":2.5,"join":"round","dash":[1,2],"dash_offset":0.5},
        \\   {"op":"fill_rect","rect":[0,0,8,8]},
        \\   {"op":"push_clip_path","path":"M0 0 L8 8 Z"},
        \\   {"op":"pop_clip_path"},
        \\   {"op":"push_clip_layer","path":"M0 0 L8 0 L8 8 Z"},
        \\   {"op":"push_layer","kind":"clip","path":"M0 0 L8 8 Z"},
        \\   {"op":"pop_layer"}
        \\ ]}
    ;
    var parsed = try parse(std.testing.allocator, text);
    defer parsed.deinit();
    try std.testing.expectEqual(@as(u16, 8), parsed.scene.width);
    try std.testing.expectEqual(@as(usize, 8), parsed.scene.commands.len);
    try std.testing.expectEqual([4]u8{ 1, 2, 3, 4 }, parsed.scene.commands[0].set_paint.solid);
    const stroke = parsed.scene.commands[1].set_stroke;
    try std.testing.expectEqual(@as(f64, 2.5), stroke.width);
    try std.testing.expectEqual(Join.round, stroke.join.?);
    try std.testing.expectEqual(@as(usize, 2), stroke.dash.?.len);
    try std.testing.expectEqualStrings("M0 0 L8 8 Z", parsed.scene.commands[3].push_clip_path);
    // `push_layer kind:clip` is equivalent to `push_clip_layer`.
    try std.testing.expectEqualStrings("M0 0 L8 0 L8 8 Z", parsed.scene.commands[5].push_clip_layer);
    try std.testing.expectEqualStrings("M0 0 L8 8 Z", parsed.scene.commands[6].push_layer.clip);
}

test "milestone 2 gradient scenes parse with expected kinds" {
    const alloc = std.testing.allocator;
    const io = std.testing.io;

    {
        var parsed = try parseSceneFile(alloc, io, "gradient_linear_64.json");
        defer parsed.deinit();
        switch (parsed.scene.commands[0].set_paint) {
            .gradient => |g| {
                try std.testing.expectEqual(@as(usize, 2), g.stops.len);
                try std.testing.expectEqual(Extend.pad, g.extend);
                try std.testing.expectEqual(@as(f64, 0.0), g.stops[0].offset);
                try std.testing.expectEqual([4]u8{ 0, 200, 64, 255 }, g.stops[0].rgba8);
                switch (g.kind) {
                    .linear => |lin| {
                        try std.testing.expectEqual([2]f64{ 10, 10 }, lin.start);
                        try std.testing.expectEqual([2]f64{ 54, 54 }, lin.end);
                    },
                    else => return error.InvalidScene,
                }
            },
            else => return error.InvalidScene,
        }
    }
    {
        var parsed = try parseSceneFile(alloc, io, "gradient_radial_64.json");
        defer parsed.deinit();
        switch (parsed.scene.commands[0].set_paint) {
            .gradient => |g| switch (g.kind) {
                .radial => |r| {
                    try std.testing.expectEqual([2]f64{ 32, 32 }, r.start_center);
                    try std.testing.expectEqual(@as(f64, 4), r.start_radius);
                    try std.testing.expectEqual([2]f64{ 32, 32 }, r.end_center);
                    try std.testing.expectEqual(@as(f64, 24), r.end_radius);
                },
                else => return error.InvalidScene,
            },
            else => return error.InvalidScene,
        }
    }
    {
        var parsed = try parseSceneFile(alloc, io, "gradient_sweep_64.json");
        defer parsed.deinit();
        switch (parsed.scene.commands[0].set_paint) {
            .gradient => |g| switch (g.kind) {
                .sweep => |s| {
                    try std.testing.expectEqual([2]f64{ 32, 32 }, s.center);
                    try std.testing.expectEqual(@as(f64, 0), s.start_angle);
                    try std.testing.expectApproxEqAbs(
                        @as(f64, 6.283185307179586),
                        s.end_angle,
                        1e-12,
                    );
                },
                else => return error.InvalidScene,
            },
            else => return error.InvalidScene,
        }
    }
    {
        var parsed = try parseSceneFile(alloc, io, "gradient_repeat_128.json");
        defer parsed.deinit();
        try std.testing.expectEqual(@as(u16, 128), parsed.scene.width);
        switch (parsed.scene.commands[0].set_paint) {
            .gradient => |g| {
                try std.testing.expectEqual(@as(usize, 3), g.stops.len);
                try std.testing.expectEqual(Extend.repeat, g.extend);
            },
            else => return error.InvalidScene,
        }
        try std.testing.expect(parsed.scene.commands[1].fill_path.len > 0);
    }
}

test "milestone 2 image scenes parse with expected samplers" {
    const alloc = std.testing.allocator;
    const io = std.testing.io;

    {
        var parsed = try parseSceneFile(alloc, io, "image_nearest_64.json");
        defer parsed.deinit();
        switch (parsed.scene.commands[0].set_paint) {
            .image => |im| {
                try std.testing.expectEqualStrings("assets/checker16.rgba", im.asset);
                try std.testing.expectEqual(@as(u16, 16), im.width);
                try std.testing.expectEqual(@as(u16, 16), im.height);
                try std.testing.expectEqual(ImageFormat.rgba8, im.format);
                try std.testing.expectEqual(ImageAlphaType.alpha, im.alpha_type);
                try std.testing.expectEqual(Extend.pad, im.sampler.x_extend);
                try std.testing.expectEqual(Extend.pad, im.sampler.y_extend);
                try std.testing.expectEqual(ImageQuality.low, im.sampler.quality);
                try std.testing.expectEqual(@as(f64, 1.0), im.sampler.alpha);
            },
            else => return error.InvalidScene,
        }
        try std.testing.expectEqual(
            Affine{ 3, 0, 0, 3, 0, 0 },
            parsed.scene.commands[1].set_paint_transform,
        );
    }
    {
        var parsed = try parseSceneFile(alloc, io, "image_bilinear_64.json");
        defer parsed.deinit();
        switch (parsed.scene.commands[0].set_paint) {
            .image => |im| {
                try std.testing.expectEqual(Extend.reflect, im.sampler.x_extend);
                try std.testing.expectEqual(Extend.reflect, im.sampler.y_extend);
                try std.testing.expectEqual(ImageQuality.medium, im.sampler.quality);
            },
            else => return error.InvalidScene,
        }
    }
}

test "milestone 2 layer and mask scenes parse with expected kinds" {
    const alloc = std.testing.allocator;
    const io = std.testing.io;

    {
        var parsed = try parseSceneFile(alloc, io, "layer_blend_multiply_64.json");
        defer parsed.deinit();
        switch (parsed.scene.commands[2].push_layer) {
            .blend => |b| {
                try std.testing.expectEqual(Mix.multiply, b.mix);
                try std.testing.expectEqual(Compose.src_over, b.compose);
            },
            else => return error.InvalidScene,
        }
        try std.testing.expectEqual(@as(usize, 6), parsed.scene.commands.len);
    }
    {
        var parsed = try parseSceneFile(alloc, io, "layer_opacity_64.json");
        defer parsed.deinit();
        try std.testing.expectEqual(
            @as(f64, 0.5),
            parsed.scene.commands[2].push_layer.opacity,
        );
        try std.testing.expectEqual(
            @as(f64, 0.5),
            parsed.scene.commands[5].push_layer.opacity,
        );
    }
    {
        var parsed = try parseSceneFile(alloc, io, "mask_alpha_64.json");
        defer parsed.deinit();
        switch (parsed.scene.commands[2].push_layer) {
            .mask => |m| {
                try std.testing.expectEqualStrings("assets/mask16.rgba", m.asset);
                try std.testing.expectEqual(@as(u16, 16), m.width);
                try std.testing.expectEqual(@as(u16, 16), m.height);
                try std.testing.expectEqual(ImageFormat.rgba8, m.format);
                try std.testing.expectEqual(ImageAlphaType.alpha, m.alpha_type);
                try std.testing.expectEqual(MaskKind.alpha, m.kind);
            },
            else => return error.InvalidScene,
        }
    }
    {
        var parsed = try parseSceneFile(alloc, io, "mask_luminance_64.json");
        defer parsed.deinit();
        switch (parsed.scene.commands[2].push_layer) {
            .mask => |m| try std.testing.expectEqual(MaskKind.luminance, m.kind),
            else => return error.InvalidScene,
        }
    }
}

test "milestone 2 filter scenes parse with expected kinds" {
    const alloc = std.testing.allocator;
    const io = std.testing.io;

    {
        var parsed = try parseSceneFile(alloc, io, "filter_flood_64.json");
        defer parsed.deinit();
        const spec = parsed.scene.commands[2].set_filter_effect;
        try std.testing.expectEqual([4]u8{ 30, 140, 220, 180 }, spec.flood);
        try std.testing.expectEqual(@as(usize, 6), parsed.scene.commands.len);
        try std.testing.expectEqual(std.meta.Tag(Command).reset_filter_effect, std.meta.activeTag(parsed.scene.commands[5]));
    }
    {
        var parsed = try parseSceneFile(alloc, io, "filter_offset_64.json");
        defer parsed.deinit();
        const spec = parsed.scene.commands[2].set_filter_effect.offset;
        try std.testing.expectEqual(@as(f64, 8.5), spec.dx);
        try std.testing.expectEqual(@as(f64, -4.0), spec.dy);
    }
    {
        var parsed = try parseSceneFile(alloc, io, "filter_gaussian_blur_64.json");
        defer parsed.deinit();
        const spec = parsed.scene.commands[2].set_filter_effect.gaussian_blur;
        try std.testing.expectEqual(@as(f64, 3.0), spec.std_deviation);
        try std.testing.expectEqual(EdgeMode.duplicate, spec.edge_mode);
    }
    {
        var parsed = try parseSceneFile(alloc, io, "filter_drop_shadow_64.json");
        defer parsed.deinit();
        const spec = parsed.scene.commands[2].set_filter_effect.drop_shadow;
        try std.testing.expectEqual(@as(f64, 6.0), spec.dx);
        try std.testing.expectEqual(@as(f64, 2.0), spec.std_deviation);
        try std.testing.expectEqual([4]u8{ 20, 30, 90, 200 }, spec.rgba8);
        try std.testing.expectEqual(EdgeMode.duplicate, spec.edge_mode);
    }
    {
        var parsed = try parseSceneFile(alloc, io, "filter_drop_shadow_only_64.json");
        defer parsed.deinit();
        const spec = parsed.scene.commands[2].set_filter_effect.drop_shadow_only;
        try std.testing.expectEqual([4]u8{ 20, 30, 90, 200 }, spec.rgba8);
    }
    {
        var parsed = try parseSceneFile(alloc, io, "filter_layer_clip_opacity_64.json");
        defer parsed.deinit();
        const spec = parsed.scene.commands[2].push_layer.filter;
        try std.testing.expectEqual([4]u8{ 30, 140, 220, 200 }, spec.filter.flood);
        try std.testing.expectEqual(@as(f64, 0.75), spec.opacity.?);
        try std.testing.expectEqual(Mix.multiply, spec.blend.?.mix);
        try std.testing.expectEqual(Compose.src_over, spec.blend.?.compose);
        try std.testing.expect(spec.clip != null);
    }
}

test "glyph_run scenes parse with expected properties" {
    const text =
        \\{"version":1,"width":64,"height":64,
        \\ "commands":[
        \\   {"op":"set_paint","rgba8":[20,40,60,255]},
        \\   {"op":"set_transform","affine":[1,0,0,1,0,0]},
        \\   {"op":"glyph_run",
        \\    "font":{"asset":"../fixtures/upstream/Roboto-Regular.ttf","index":0},
        \\    "font_size":20.0,"hint":false,"atlas_cache":true,"style":"fill",
        \\    "glyph_transform":[1,0,0.2,1,0,0],
        \\    "glyphs":[{"id":43,"x":1.5,"y":0.0},{"id":72,"x":3.25,"y":0.0}]}
        \\ ]}
    ;
    var parsed = try parse(std.testing.allocator, text);
    defer parsed.deinit();
    const spec = parsed.scene.commands[2].glyph_run;
    try std.testing.expectEqualStrings(
        "../fixtures/upstream/Roboto-Regular.ttf",
        spec.font.asset,
    );
    try std.testing.expectEqual(@as(u32, 0), spec.font.index);
    try std.testing.expectEqual(@as(f32, 20.0), spec.font_size);
    try std.testing.expect(!spec.hint);
    try std.testing.expect(spec.atlas_cache);
    try std.testing.expectEqual(GlyphStyle.fill, spec.style);
    try std.testing.expectEqual(Affine{ 1, 0, 0.2, 1, 0, 0 }, spec.glyph_transform.?);
    try std.testing.expectEqual(@as(usize, 2), spec.glyphs.len);
    try std.testing.expectEqual(@as(u32, 43), spec.glyphs[0].id);
    try std.testing.expectEqual(@as(f32, 1.5), spec.glyphs[0].x);
    try std.testing.expectEqual(@as(f32, 3.25), spec.glyphs[1].x);

    // Optional knobs (embolden and normalized_coords are implemented) parse
    // and are carried through.
    const deferred =
        \\{"version":1,"width":8,"height":8,
        \\ "commands":[{"op":"glyph_run",
        \\   "font":{"asset":"f.ttf"},"font_size":12.0,"style":"stroke",
        \\   "embolden":[0.5,0.0],"normalized_coords":[1.0,-0.5],
        \\   "decoration":{"x_range":[0,10],"baseline_y":5,"offset":1,"size":2,"buffer":0.5},
        \\   "glyphs":[{"id":1,"x":0,"y":0}]}]}
    ;
    var deferred_parsed = try parse(std.testing.allocator, deferred);
    defer deferred_parsed.deinit();
    const deferred_spec = deferred_parsed.scene.commands[0].glyph_run;
    try std.testing.expectEqual(GlyphStyle.stroke, deferred_spec.style);
    try std.testing.expectEqual([2]f32{ 0.5, 0.0 }, deferred_spec.embolden.?);
    try std.testing.expectEqual(@as(f32, 1.0), deferred_spec.normalized_coords.?[0]);
    try std.testing.expectEqual(@as(f32, -0.5), deferred_spec.normalized_coords.?[1]);
    try std.testing.expectEqual(@as(f32, 0.5), deferred_spec.decoration.?.buffer);
}

test "invalid scenes are rejected" {
    try std.testing.expectError(error.InvalidScene, parse(std.testing.allocator, "{}"));
    try std.testing.expectError(
        error.InvalidScene,
        parse(std.testing.allocator, "{\"version\":2,\"width\":1,\"height\":1}"),
    );
    try std.testing.expectError(
        error.InvalidScene,
        parse(std.testing.allocator, "{\"version\":1,\"width\":1,\"height\":1,\"commands\":[{\"op\":\"nope\"}]}"),
    );
    // set_paint requires exactly one variant.
    try std.testing.expectError(
        error.InvalidScene,
        parse(
            std.testing.allocator,
            "{\"version\":1,\"width\":1,\"height\":1,\"commands\":[{\"op\":\"set_paint\"}]}",
        ),
    );
    try std.testing.expectError(
        error.InvalidScene,
        parse(
            std.testing.allocator,
            "{\"version\":1,\"width\":1,\"height\":1,\"commands\":[{\"op\":\"set_paint\",\"rgba8\":[1,2,3,4],\"gradient\":{}}]}",
        ),
    );
    // Unknown gradient kinds, sampler values and layer kinds are rejected.
    try std.testing.expectError(
        error.InvalidScene,
        parse(
            std.testing.allocator,
            "{\"version\":1,\"width\":1,\"height\":1,\"commands\":[{\"op\":\"set_paint\",\"gradient\":{\"kind\":{\"conic\":{}},\"stops\":[],\"extend\":\"pad\"}}]}",
        ),
    );
    try std.testing.expectError(
        error.InvalidScene,
        parse(
            std.testing.allocator,
            "{\"version\":1,\"width\":1,\"height\":1,\"commands\":[{\"op\":\"set_paint\",\"gradient\":{\"kind\":{\"linear\":{\"start\":[0,0],\"end\":[1,1]}},\"stops\":[],\"extend\":\"clamp\"}}]}",
        ),
    );
    try std.testing.expectError(
        error.InvalidScene,
        parse(
            std.testing.allocator,
            "{\"version\":1,\"width\":1,\"height\":1,\"commands\":[{\"op\":\"set_paint\",\"image\":{\"asset\":\"a.rgba\",\"width\":1,\"height\":1,\"format\":\"rgba8\",\"alpha_type\":\"alpha\",\"sampler\":{\"x_extend\":\"pad\",\"y_extend\":\"pad\",\"quality\":\"ultra\",\"alpha\":1.0}}}]}",
        ),
    );
    // A filter layer without a `filter` payload is rejected.
    try std.testing.expectError(
        error.InvalidScene,
        parse(
            std.testing.allocator,
            "{\"version\":1,\"width\":1,\"height\":1,\"commands\":[{\"op\":\"push_layer\",\"kind\":\"filter\"}]}",
        ),
    );
    // Unknown filter kinds are rejected.
    try std.testing.expectError(
        error.InvalidScene,
        parse(
            std.testing.allocator,
            "{\"version\":1,\"width\":1,\"height\":1,\"commands\":[{\"op\":\"set_filter_effect\",\"filter\":{\"kind\":\"convolve\"}}]}",
        ),
    );
    try std.testing.expectError(
        error.InvalidScene,
        parse(
            std.testing.allocator,
            "{\"version\":1,\"width\":1,\"height\":1,\"commands\":[{\"op\":\"push_layer\",\"kind\":\"mask\",\"mask\":{\"asset\":\"a.rgba\",\"width\":1,\"height\":1,\"format\":\"rgba8\",\"alpha_type\":\"alpha\",\"kind\":\"chroma\"}}]}",
        ),
    );
}

fn parseSceneFile(
    alloc: std.mem.Allocator,
    io: std.Io,
    name: []const u8,
) ParseError!Parsed {
    var dir = std.Io.Dir.cwd().openDir(io, "tests/scenes", .{}) catch return error.InvalidScene;
    defer dir.close(io);
    const text = dir.readFileAlloc(io, name, alloc, .unlimited) catch return error.InvalidScene;
    defer alloc.free(text);
    return parse(alloc, text);
}
