/*
 * bindings.h - umbrella include for the wgpu-native C API.
 *
 * This header is intentionally tiny: it pulls in the two upstream headers that
 * together define the complete C ABI exposed by wgpu-native:
 *
 *   - webgpu/webgpu.h : the WebGPU C API (webgpu-headers submodule)
 *   - webgpu/wgpu.h   : wgpu-native specific extensions
 *   - wgpu_init.h     : generated shims for the WGPU_*_INIT initializer macros
 *
 * The first two files are byte-for-byte copies of the upstream headers at the
 * pinned revision (see README.md and tools/fetch-reference.sh). Do not edit
 * them by hand. wgpu_init.h is generated by tools/gen_init_shims.py.
 *
 * wgpu.h includes webgpu.h itself, but the explicit include below makes the
 * relationship obvious and works with either include order.
 */
#ifndef WGPU_ZIG_BINDINGS_H_
#define WGPU_ZIG_BINDINGS_H_

#include "webgpu/webgpu.h"
#include "webgpu/wgpu.h"
#include "wgpu_init.h"

#endif /* WGPU_ZIG_BINDINGS_H_ */
