//! C API bindings for HarfBuzz.
//!
//! Zig 0.17 removed `@cImport`, so these bindings are generated by
//! `zig translate-c` from the system HarfBuzz headers (14.1.0):
//!
//!   zig translate-c -I/usr/include/harfbuzz -I/usr/include/freetype2 \
//!       -I/usr/include -I/usr/include/libpng16 <hb.h + hb-ft.h> \
//!       > src/harfbuzz/c_bindings.zig
//!
//! The library code in this directory (`buffer.zig`, `font.zig`, ...) refers
//! to `c.hb_*` names exactly as the original `@cImport` version did.
pub const c = @import("c_bindings.zig");
