//! Port of vello_common encode.rs (Apache-2.0 OR MIT).
//!
//! Paint encoding for the sparse-strip renderer: `EncodedPaint` (gradient,
//! image, blurred rounded rectangle) plus the gradient range/LUT machinery the
//! fine rasterizer samples from.
//!
//! Scope decisions (numbered as in the port task; every divergence from the
//! upstream file is called out here):
//!
//! 1. **sRGB-only stops.** `ColorStop.color` is `AlphaColor(Srgb)` in this
//!    port, so the sRGB branch of upstream `encode_stops` is transcribed
//!    directly: each adjacent stop pair becomes one `GradientRange` with
//!    `bias + x * scale` interpolation. Upstream's `color::gradient` /
//!    `gradient_unpremultiplied` expansion (which subdivides the range with
//!    extra interpolated stops for other color spaces) is not ported; a
//!    gradient whose `interpolation_cs` is not sRGB returns
//!    `error.Unsupported` instead of silently approximating with sRGB.
//!    `GradientCacheKey` still carries `stops`, `interpolation_cs`, and
//!    `hue_direction` for structural fidelity.
//!    `InterpolationAlphaSpace` is handled exactly as upstream: premultiplied
//!    ranges store premultiplied colors; unpremultiplied ranges store straight
//!    colors and the LUT premultiplies them at generation time.
//! 2. **Validation matches upstream.** Empty stops produce a black solid
//!    paint, one stop produces that stop's color, and invalid offsets/kinds
//!    produce the first stop's color (upstream returns these fallbacks rather
//!    than panicking). Offsets must be in `[0, 1]` (NaN is invalid) and
//!    non-decreasing; missing first/last offsets are padded to 0/1 with copies
//!    of the first/last stop. Degenerate linear gradients use
//!    `DEGENERATE_THRESHOLD = 1e-6`; radial validates negative radii and
//!    coincident center/radius pairs; sweep requires
//!    `end_angle > start_angle` and a delta larger than the threshold.
//!    `NUDGE_VAL = 1e-7` guards the range divisor.
//! 3. **Radial gradients** (the Skia conical algorithm) are ported including
//!    `FocalData` (`create`/`is_focal_on_circle`/`is_swapped`/
//!    `is_well_behaved`/`is_natively_focal`) and `RadialKind::has_undefined`.
//! 4. **Gradient LUTs** exist for both `u8` and `f32`, generated by the same
//!    vector math as upstream through the ported `src/simd/root.zig` helpers:
//!    `elementWiseSplat`, `splat4thPerGroup`, `blockSplat`, and
//!    `simd.mulAddUnfused`. Fused multiply-add would not match upstream's
//!    portable/baseline backends, matching the convention set by
//!    `common/strip.zig`. `GradientLutExt` is a namespace (Zig has no traits)
//!    selected by the `T` parameter.
//! 5. **Lazy LUT storage.** Upstream uses `OnceCell` (single-threaded) or
//!    `OnceLock` (multithreading); this port stores `?GradientLut` and
//!    initializes on first `u8Lut`/`f32Lut` access. Those accessors take
//!    `*EncodedGradient` and mutate through the pointer, so they are
//!    single-threaded for now; M4 adds synchronization. Allocation failure
//!    propagates (`error.OutOfMemory`) and leaves the cell empty.
//! 6. **Images**: `EncodedImage` keeps upstream's fields and computes the same
//!    inverse transform, x/y advances, and transparency flag. `sampler.alpha`
//!    is folded into the tint color's alpha (creating a white multiply tint
//!    when there is none) and clamped to 1, and `ImageQuality.medium` is
//!    downgraded to `.low` for integer-only translations.
//! 7. **Blurred rounded rectangles**: `EncodedBlurredRoundedRectangle` is
//!    declared with upstream's fields but its encoder returns
//!    `error.Unsupported`; the algorithm belongs to the filters/BRR work
//!    (M2-later) and no field is faked.
//! 8. `EncodedPaint.mayHaveTransparency` and the `Paint`-level query are
//!    ported; the transparent-source path works for images whose pixels are
//!    resolved later through `NoOpImageResolver`, because the flag comes from
//!    the `ImageSource` transparency hint or a translucent tint.
//!
//! Ownership/allocator note: `EncodeExt` equivalents take an explicit
//! allocator. `EncodedGradient` owns its `ranges` slice and the cloned stops
//! in `cache_key`; `EncodedImage` owns one `ImageSource` reference.
//! `deinit(allocator)` releases exactly those resources, and
//! `Paint`/`IndexedPaint` values pushed into `paints` are owned by the caller.
//! `GradientLut(T)` owns its lookup table. Nothing is freed implicitly.

const std = @import("std");
const simd = @import("../simd/root.zig");
const kurbo = @import("../kurbo/root.zig");
const peniko = @import("../peniko/root.zig");
const math = @import("math.zig");
const util = @import("util.zig");
const paint_mod = @import("paint.zig");
const blurred_rounded_rect_mod = @import("blurred_rounded_rect.zig");

const Affine = kurbo.Affine;
const Point = kurbo.Point;
const Vec2 = kurbo.Vec2;

const AlphaColor = peniko.AlphaColor;
const Color = peniko.Color;
const ColorSpaceTag = peniko.color.ColorSpaceTag;
const ColorStop = peniko.ColorStop;
const ColorStops = peniko.ColorStops;
const Extend = peniko.Extend;
const Gradient = peniko.Gradient;
const HueDirection = peniko.color.HueDirection;
const ImageQuality = peniko.ImageQuality;
const ImageSampler = peniko.ImageSampler;
const InterpolationAlphaSpace = peniko.InterpolationAlphaSpace;
const Srgb = peniko.Srgb;

const Image = paint_mod.Image;
const ImageSource = paint_mod.ImageSource;
const IndexedPaint = paint_mod.IndexedPaint;
const Paint = paint_mod.Paint;
const PremulColor = paint_mod.PremulColor;
const Tint = paint_mod.Tint;
const TintMode = paint_mod.TintMode;

const BlurredRoundedRectangle = blurred_rounded_rect_mod.BlurredRoundedRectangle;

const F32x4 = simd.F32x4;
const F32x16 = simd.F32x16;

/// Upstream `DEGENERATE_THRESHOLD`: points/values closer than this make a
/// gradient degenerate.
const DEGENERATE_THRESHOLD: f32 = 1.0e-6;

/// Upstream `NUDGE_VAL`: minimum divisor used when building a gradient range,
/// so padded stops at the same offset still produce a finite scale.
const NUDGE_VAL: f32 = 1.0e-7;

/// The maximum size of the gradient LUT (upstream `MAX_GRADIENT_LUT_SIZE`).
pub const MAX_GRADIENT_LUT_SIZE: usize = 4096;

/// Errors produced while encoding a paint.
pub const Error = error{
    /// The paint needs an algorithm this port does not implement (non-sRGB
    /// gradient interpolation, blurred rounded rectangles).
    Unsupported,
    /// An `IndexedPaint` index does not fit into `u32` (upstream panics).
    TooManyPaints,
    /// An owned allocation failed; the output list is unchanged.
    OutOfMemory,
};

// ---------------------------------------------------------------------------
// Paint encoding entry points (upstream `EncodeExt`)
// ---------------------------------------------------------------------------

/// Zig face of upstream's `EncodeExt` trait: callers dispatch on the paint
/// type at compile time. `Gradient`, `Image`, and `BlurredRoundedRectangle`
/// are accepted by value or by pointer; passing by value is a shallow borrow
/// (the encoder clones what it stores and never frees the input).
pub const EncodeExt = struct {
    pub const encodeInto = dispatchEncode;
};

/// Encode `value` and append the encoded paint to `paints`, returning the
/// corresponding indexed (or fallback solid) `Paint`.
pub fn encodeInto(
    value: anytype,
    allocator: std.mem.Allocator,
    paints: *std.ArrayList(EncodedPaint),
    transform: Affine,
    tint: ?Tint,
) Error!Paint {
    return dispatchEncode(value, allocator, paints, transform, tint);
}

fn dispatchEncode(
    value: anytype,
    allocator: std.mem.Allocator,
    paints: *std.ArrayList(EncodedPaint),
    transform: Affine,
    tint: ?Tint,
) Error!Paint {
    const V = @TypeOf(value);
    if (V == Gradient or V == *const Gradient or V == *Gradient) {
        const gradient: *const Gradient = if (@typeInfo(V) == .pointer) value else &value;
        return encodeGradient(gradient, allocator, paints, transform, tint);
    }
    if (V == Image or V == *const Image or V == *Image) {
        const image: *const Image = if (@typeInfo(V) == .pointer) value else &value;
        return encodeImage(image, allocator, paints, transform, tint);
    }
    if (V == BlurredRoundedRectangle or V == *const BlurredRoundedRectangle or V == *BlurredRoundedRectangle) {
        const rect: *const BlurredRoundedRectangle = if (@typeInfo(V) == .pointer) value else &value;
        return encodeBlurredRoundedRectangle(rect, allocator, paints, transform, tint);
    }
    @compileError("EncodeExt.encodeInto: unsupported paint type " ++ @typeName(V));
}

// ---------------------------------------------------------------------------
// Gradient encoding
// ---------------------------------------------------------------------------

/// Encode a gradient into `paints` and return its indexed paint.
///
/// Invalid gradients return a solid fallback paint without touching `paints`,
/// exactly like upstream `validate`.
pub fn encodeGradient(
    gradient: *const Gradient,
    allocator: std.mem.Allocator,
    paints: *std.ArrayList(EncodedPaint),
    transform: Affine,
    tint: ?Tint,
) Error!Paint {
    // Upstream ignores the tint for gradients (`_tint`).
    _ = tint;

    if (validate(gradient)) |fallback| return fallback;

    const idx = paints.items.len;
    const indexed = try IndexedPaint.new(idx);

    var may_have_transparency = false;
    for (gradient.stops.items) |stop| {
        if (stop.color.components[3] != 1.0) {
            may_have_transparency = true;
            break;
        }
    }

    // Pad missing first/last offsets to 0/1 so the ranges cover the whole
    // gradient. Ownership: `padded_stops` is a temporary copy released before
    // returning; the original gradient stays borrowed.
    var padded_stops: ?[]ColorStop = null;
    defer if (padded_stops) |padded| allocator.free(padded);
    var stops: []const ColorStop = gradient.stops.items;
    {
        const first = stops[0];
        const last = stops[stops.len - 1];
        if (first.offset != 0.0 or last.offset != 1.0) {
            const pad_first: usize = if (first.offset != 0.0) 1 else 0;
            const pad_last: usize = if (last.offset != 1.0) 1 else 0;
            const padded = try allocator.alloc(ColorStop, stops.len + pad_first + pad_last);
            padded_stops = padded;
            var at: usize = 0;
            if (pad_first == 1) {
                padded[0] = .{ .offset = 0.0, .color = first.color };
                at = 1;
            }
            @memcpy(padded[at..][0..stops.len], stops);
            if (pad_last == 1) {
                padded[at + stops.len] = .{ .offset = 1.0, .color = last.color };
            }
            stops = padded;
        }
    }

    var base_transform: Affine = undefined;
    var kind: EncodedKind = undefined;
    switch (gradient.kind) {
        .linear => |pos| {
            // Map the gradient line to (0, 0) -> (1, 0) so the position along
            // the line is just the interpolated x coordinate.
            base_transform = tsFromLineToLine(pos.start, pos.end, Point.ZERO, Point.new(1.0, 0.0));
            kind = .{ .linear = .{} };
        },
        .radial => |pos| {
            // Translated from Skia's conical gradient implementation:
            // <https://skia.org/docs/dev/design/conical/>
            const c0 = pos.start_center;
            const c1 = pos.end_center;
            const r0 = pos.start_radius;
            const r1 = pos.end_radius;
            const d_radius = r1 - r0;

            const center_distance: f32 = @floatCast(c1.subPoint(c0).length());
            if (math.isNearlyZero(center_distance)) {
                base_transform = Affine.translate(Vec2.new(-c1.x, -c1.y));
                base_transform = base_transform.thenScale(1.0 / @as(f64, @floatCast(@max(r0, r1))));

                const scale = @max(r1, r0) / d_radius;
                const bias = -r0 / d_radius;
                kind = .{ .radial = .{ .radial = .{ .bias = bias, .scale = scale } } };
            } else {
                base_transform = tsFromLineToLine(c0, c1, Point.ZERO, Point.new(1.0, 0.0));

                if (math.isNearlyZero(r1 - r0)) {
                    const scaled_r0 = r1 / center_distance;
                    kind = .{ .radial = .{ .strip = .{
                        .scaled_r0_squared = scaled_r0 * scaled_r0,
                    } } };
                } else {
                    const d_center: f32 = @floatCast(c0.subPoint(c1).length());
                    const focal_data = FocalData.create(r0 / d_center, r1 / d_center, &base_transform);
                    const fp0 = 1.0 / focal_data.fr1;
                    const fp1 = focal_data.f_focal_x;
                    kind = .{ .radial = .{ .focal = .{
                        .focal_data = focal_data,
                        .fp0 = fp0,
                        .fp1 = fp1,
                    } } };
                }
            }
        },
        .sweep => |pos| {
            // Move the center to the origin so the angle is measured from (0, 0).
            const x_offset: f32 = @floatCast(-pos.center.x);
            const y_offset: f32 = @floatCast(-pos.center.y);
            base_transform = Affine.translate(Vec2.new(x_offset, y_offset));

            kind = .{
                .sweep = .{
                    .start_angle = pos.start_angle,
                    // Store the inverse so the renderer can multiply.
                    .inv_angle_delta = 1.0 / (pos.end_angle - pos.start_angle),
                },
            };
        },
    }

    const has_undefined = kind.hasUndefined();
    may_have_transparency = may_have_transparency or has_undefined;

    const ranges = try encodeStops(
        allocator,
        stops,
        gradient.interpolation_cs,
        gradient.hue_direction,
        gradient.interpolation_alpha_space,
    );
    errdefer allocator.free(ranges);

    // Shader base transform followed by the inverse paint transform, so the
    // renderer can start from the first pixel of a span and advance.
    const encoded_transform = base_transform.compose(transform.inverse());
    const advances = xYAdvances(encoded_transform);

    var cache_key = GradientCacheKey{
        .stops = try gradient.stops.clone(allocator),
        .interpolation_cs = gradient.interpolation_cs,
        .hue_direction = gradient.hue_direction,
    };
    errdefer cache_key.stops.deinit();

    const encoded = EncodedGradient{
        .cache_key = cache_key,
        .kind = kind,
        .has_undefined = has_undefined,
        .transform = encoded_transform,
        .x_advance = advances.x_advance,
        .y_advance = advances.y_advance,
        .ranges = ranges,
        .extend = gradient.extend,
        .may_have_transparency = may_have_transparency,
    };

    try paints.append(allocator, .{ .gradient = encoded });
    return .{ .indexed = indexed };
}

/// Returns a fallback paint in case the gradient is invalid: black if there
/// are no stops, otherwise the first stop's color. A `null` result means the
/// gradient is valid.
fn validate(gradient: *const Gradient) ?Paint {
    const black = Paint.fromAlphaColor(peniko.palette.css.BLACK);

    // Gradients need at least two stops.
    if (gradient.stops.items.len == 0) return black;

    const first = Paint.fromAlphaColor(gradient.stops.items[0].color);
    if (gradient.stops.items.len == 1) return first;

    for (gradient.stops.items[0 .. gradient.stops.items.len - 1], gradient.stops.items[1..]) |f, n| {
        // Offsets must be between 0 and 1, and not NaN.
        if (!(f.offset >= 0.0 and f.offset <= 1.0)) return first;
        // Stops must be sorted by ascending offset.
        if (f.offset > n.offset) return first;
    }

    const last = gradient.stops.items[gradient.stops.items.len - 1];
    if (!(last.offset >= 0.0 and last.offset <= 1.0)) return first;

    switch (gradient.kind) {
        .linear => |pos| {
            if (degeneratePoint(pos.start, pos.end)) return first;
        },
        .radial => |pos| {
            // Radii must not be negative.
            if (pos.start_radius < 0.0 or pos.end_radius < 0.0) return first;
            // Radii and center points must not be close to the same.
            if (degeneratePoint(pos.start_center, pos.end_center) and
                degenerateVal(pos.start_radius, pos.end_radius))
            {
                return first;
            }
        },
        .sweep => |pos| {
            // The end angle must be larger than the start angle.
            if (degenerateVal(pos.start_angle, pos.end_angle)) return first;
            if (pos.end_angle <= pos.start_angle) return first;
        },
    }

    return null;
}

fn degeneratePoint(p1: Point, p2: Point) bool {
    return @as(f32, @floatCast(@abs(p1.x - p2.x))) <= DEGENERATE_THRESHOLD and
        @as(f32, @floatCast(@abs(p1.y - p2.y))) <= DEGENERATE_THRESHOLD;
}

fn degenerateVal(v1: f32, v2: f32) bool {
    return @abs(v2 - v1) <= DEGENERATE_THRESHOLD;
}

/// A color stop with its color converted to straight-alpha sRGB (upstream's
/// private `EncodedColorStop`).
const EncodedColorStop = struct {
    offset: f32,
    color: AlphaColor(Srgb),
};

/// Encode all stops into a sequence of ranges.
///
/// The sRGB interpolation path is a direct transcription; see scope decision 1
/// for why other color spaces return `error.Unsupported`.
fn encodeStops(
    allocator: std.mem.Allocator,
    stops: []const ColorStop,
    cs: ColorSpaceTag,
    hue_dir: HueDirection,
    interpolation_alpha_space: InterpolationAlphaSpace,
) Error![]GradientRange {
    _ = hue_dir;

    if (cs != .srgb) return error.Unsupported;

    const ranges = try allocator.alloc(GradientRange, stops.len - 1);
    errdefer allocator.free(ranges);

    for (stops[0 .. stops.len - 1], stops[1..], 0..) |left, right, i| {
        ranges[i] = createRange(
            .{ .offset = left.offset, .color = left.color },
            .{ .offset = right.offset, .color = right.color },
            interpolation_alpha_space,
        );
    }
    return ranges;
}

/// Build a single `GradientRange` between two stops.
fn createRange(
    left_stop: EncodedColorStop,
    right_stop: EncodedColorStop,
    interpolation_alpha_space: InterpolationAlphaSpace,
) GradientRange {
    const x0 = left_stop.offset;
    const x1 = right_stop.offset;

    const c0 = clampColor(if (interpolation_alpha_space == .unpremultiplied)
        left_stop.color.components
    else
        left_stop.color.premultiply().components);
    const c1 = clampColor(if (interpolation_alpha_space == .unpremultiplied)
        right_stop.color.components
    else
        right_stop.color.premultiply().components);

    // Calculate a bias and scale such that `bias + x * scale` interpolates
    // between the two colors. The nudge guards padded stops at equal offsets.
    const x1_minus_x0 = @max(x1 - x0, NUDGE_VAL);
    var scale: [4]f32 = undefined;
    var bias: [4]f32 = undefined;
    for (0..4) |i| {
        scale[i] = (c1[i] - c0[i]) / x1_minus_x0;
        bias[i] = c0[i] - x0 * scale[i];
    }

    return .{
        .x1 = x1,
        .bias = bias,
        .scale = scale,
        .interpolation_alpha_space = interpolation_alpha_space,
    };
}

/// Clamp a color to `[0, 1]`, preserving NaN like Rust's `f32::clamp` (`@min`
/// and `@max` would replace it).
fn clampColor(components: [4]f32) [4]f32 {
    var out = components;
    for (&out) |*c| {
        if (c.* < 0.0) {
            c.* = 0.0;
        } else if (c.* > 1.0) {
            c.* = 1.0;
        }
    }
    return out;
}

/// The transform that maps the first pixel of a span to the next one. See the
/// upstream comment in `encode.rs`: pixels are processed column-major, so the
/// renderer advances by `x_advance`/`y_advance` instead of applying the full
/// transform per pixel.
pub fn xYAdvances(transform: Affine) Advances {
    const c = transform.asCoeffs();
    const scale_skew_transform = Affine.new(.{ c[0], c[1], c[2], c[3], 0.0, 0.0 });

    const x_advance = scale_skew_transform.transformPoint(Point.new(1.0, 0.0));
    const y_advance = scale_skew_transform.transformPoint(Point.new(0.0, 1.0));

    return .{
        .x_advance = Vec2.new(x_advance.x, x_advance.y),
        .y_advance = Vec2.new(y_advance.x, y_advance.y),
    };
}

/// The per-step position deltas returned by [`xYAdvances`].
pub const Advances = struct {
    /// Advance in paint coordinates for one step in the x direction.
    x_advance: Vec2,
    /// Advance in paint coordinates for one step in the y direction.
    y_advance: Vec2,
};

/// Calculate the transform mapping the line spanned by `src1`, `src2` to the
/// line spanned by `dst1`, `dst2`.
///
/// Copied from tiny-skia (via upstream vello_common):
/// <https://github.com/linebender/tiny-skia/blob/68b198a7210a6bbf752b43d6bc4db62445730313/src/shaders/radial_gradient.rs#L182>
fn tsFromLineToLine(src1: Point, src2: Point, dst1: Point, dst2: Point) Affine {
    const unit_to_line1 = unitToLine(src1, src2);
    const line1_to_unit = unit_to_line1.inverse();
    const unit_to_line2 = unitToLine(dst1, dst2);
    return unit_to_line2.compose(line1_to_unit);
}

/// The transform mapping the unit vector to the line spanned by `p0`, `p1`.
fn unitToLine(p0: Point, p1: Point) Affine {
    return Affine.new(.{
        p1.y - p0.y,
        p0.x - p1.x,
        p1.x - p0.x,
        p1.y - p0.y,
        p0.x,
        p0.y,
    });
}

// ---------------------------------------------------------------------------
// Encoded paints
// ---------------------------------------------------------------------------

/// An encoded paint.
pub const EncodedPaint = union(enum) {
    /// An encoded gradient.
    gradient: EncodedGradient,
    /// An encoded image.
    image: EncodedImage,
    /// A blurred, rounded rectangle.
    blurred_rounded_rect: EncodedBlurredRoundedRectangle,

    /// Returns whether this encoded paint may produce non-opaque pixels.
    pub fn mayHaveTransparency(self: EncodedPaint) bool {
        return switch (self) {
            .gradient => |gradient| gradient.may_have_transparency,
            .image => |image| image.may_have_transparency,
            .blurred_rounded_rect => true,
        };
    }

    /// Release the resources owned by this paint.
    pub fn deinit(self: *EncodedPaint, allocator: std.mem.Allocator) void {
        switch (self.*) {
            .gradient => |*gradient| gradient.deinit(allocator),
            .image => |*image| image.deinit(allocator),
            .blurred_rounded_rect => {},
        }
        self.* = undefined;
    }
};

/// Upstream `impl Paint`: whether the paint may produce non-opaque pixels.
///
/// `encoded_paints` must be the list the paint's index refers to.
pub fn paintMayHaveTransparency(paint: Paint, encoded_paints: []const EncodedPaint) bool {
    return switch (paint) {
        .solid => |color| !color.isOpaque(),
        .indexed => |index| encoded_paints[index.index()].mayHaveTransparency(),
    };
}

/// An encoded image.
pub const EncodedImage = struct {
    /// The underlying source of the image.
    source: ImageSource,
    /// Sampling parameters (with `alpha` folded into the tint).
    sampler: ImageSampler,
    /// Whether the image may produce non-opaque pixels.
    may_have_transparency: bool,
    /// The inverse image transform to apply to the first pixel of a span.
    transform: Affine,
    /// The advance in image coordinates for one step in the x direction.
    x_advance: Vec2,
    /// The advance in image coordinates for one step in the y direction.
    y_advance: Vec2,
    /// Optional tint applied to the image.
    tint: ?Tint,

    /// Release the owned image source reference (or pixmap handle).
    pub fn deinit(self: *EncodedImage, allocator: std.mem.Allocator) void {
        self.source.deinit(allocator);
        self.* = undefined;
    }
};

/// Encode an image into `paints` and return its indexed paint.
pub fn encodeImage(
    image: *const Image,
    allocator: std.mem.Allocator,
    paints: *std.ArrayList(EncodedPaint),
    transform: Affine,
    tint: ?Tint,
) Error!Paint {
    const idx = paints.items.len;
    const indexed = try IndexedPaint.new(idx);

    var sampler = image.sampler;
    var encoded_tint = tint;

    // An additional sampler alpha multiplier is folded into the tint's alpha
    // channel so the rasterizer only has to handle a single opacity.
    if (sampler.alpha != 1.0) {
        if (encoded_tint == null) {
            encoded_tint = Tint{ .color = Color.WHITE, .mode = .multiply };
        }
        if (encoded_tint) |*t| {
            const alpha = @min(t.color.components[3] * sampler.alpha, 1.0);
            t.color = t.color.withAlpha(alpha);
        }
        sampler.alpha = 1.0;
    }

    const c = transform.asCoeffs();

    // Optimize image quality for integer-only translations.
    if (math.isNearlyZero(@as(f32, @floatCast(c[0])) - 1.0) and
        math.isNearlyZero(@as(f32, @floatCast(c[1]))) and
        math.isNearlyZero(@as(f32, @floatCast(c[2]))) and
        math.isNearlyZero(@as(f32, @floatCast(c[3])) - 1.0) and
        math.isNearlyZero(@as(f32, @floatCast(c[4] - @floor(c[4])))) and
        math.isNearlyZero(@as(f32, @floatCast(c[5] - @floor(c[5])))) and
        sampler.quality == .medium)
    {
        sampler.quality = .low;
    }

    const encoded_transform = transform.inverse();
    const advances = xYAdvances(encoded_transform);

    // If the tint color has alpha < 1.0, the image will have opacities even if
    // the source pixels are all opaque.
    const has_opacity = if (encoded_tint) |t| t.color.components[3] < 1.0 else false;

    var encoded = EncodedImage{
        .source = image.image.clone(),
        .sampler = sampler,
        .may_have_transparency = image.image.mayHaveTransparency() or has_opacity,
        .transform = encoded_transform,
        .x_advance = advances.x_advance,
        .y_advance = advances.y_advance,
        .tint = encoded_tint,
    };
    errdefer encoded.deinit(allocator);

    try paints.append(allocator, .{ .image = encoded });
    return .{ .indexed = indexed };
}

/// A blurred, rounded rectangle. Fields match upstream; the encoder itself is
/// scope decision 7 (M2-later, `error.Unsupported`).
pub const EncodedBlurredRoundedRectangle = struct {
    /// A component for computing the blur effect.
    exponent: f32,
    /// A component for computing the blur effect.
    recip_exponent: f32,
    /// A component for computing the blur effect.
    scale: f32,
    /// A component for computing the blur effect.
    std_dev_inv: f32,
    /// A component for computing the blur effect.
    min_edge: f32,
    /// A component for computing the blur effect.
    w: f32,
    /// A component for computing the blur effect.
    h: f32,
    /// A component for computing the blur effect.
    width: f32,
    /// A component for computing the blur effect.
    height: f32,
    /// A component for computing the blur effect.
    r1: f32,
    /// Whether to paint the inverse (`1 - alpha`) of the blur coverage.
    invert: bool,
    /// The base color for the blurred rectangle.
    color: PremulColor,
    /// A transform that needs to be applied to the position of the first pixel.
    transform: Affine,
    /// How much to advance for one step in the x direction.
    x_advance: Vec2,
    /// How much to advance for one step in the y direction.
    y_advance: Vec2,
};

/// Upstream `EncodeExt for BlurredRoundedRectangle`.
///
/// Deferred to the filters/BRR work (M2-later). The upstream implementation
/// computes exponent/scale/min-edge fields from `compute_erf7` and the blur
/// std-dev; this port refuses to guess any of them and fails explicitly.
pub fn encodeBlurredRoundedRectangle(
    rect: *const BlurredRoundedRectangle,
    allocator: std.mem.Allocator,
    paints: *std.ArrayList(EncodedPaint),
    transform: Affine,
    tint: ?Tint,
) Error!Paint {
    _ = rect;
    _ = allocator;
    _ = paints;
    _ = transform;
    _ = tint;
    return error.Unsupported;
}

// ---------------------------------------------------------------------------
// Focal / radial data (Skia conical gradients)
// ---------------------------------------------------------------------------

/// Computed properties of a linear gradient (upstream `LinearKind`).
pub const LinearKind = struct {};

/// Focal data for a two-point radial gradient.
pub const FocalData = struct {
    /// The normalized radius of the outer circle in focal space.
    fr1: f32,
    /// The x-coordinate of the focal point in normalized space.
    f_focal_x: f32,
    /// Whether the focal points have been swapped.
    f_is_swapped: bool,

    /// Create new focal data with the given radii and update `matrix`.
    pub fn create(r0_in: f32, r1_in: f32, matrix: *Affine) FocalData {
        var r0 = r0_in;
        var r1 = r1_in;
        var swapped = false;
        var f_focal_x = r0 / (r0 - r1);

        if (math.isNearlyZero(f_focal_x - 1.0)) {
            matrix.* = matrix.thenTranslate(Vec2.new(-1.0, 0.0));
            matrix.* = matrix.thenScaleNonUniform(-1.0, 1.0);
            std.mem.swap(f32, &r0, &r1);
            f_focal_x = 0.0;
            swapped = true;
        }

        const focal_matrix = tsFromLineToLine(
            Point.new(f_focal_x, 0.0),
            Point.new(1.0, 0.0),
            Point.new(0.0, 0.0),
            Point.new(1.0, 0.0),
        );
        matrix.* = focal_matrix.compose(matrix.*);

        const fr1 = r1 / @abs(1.0 - f_focal_x);

        const data = FocalData{
            .fr1 = fr1,
            .f_focal_x = f_focal_x,
            .f_is_swapped = swapped,
        };

        if (data.isFocalOnCircle()) {
            matrix.* = matrix.thenScale(0.5);
        } else {
            matrix.* = matrix.thenScaleNonUniform(
                @as(f64, fr1 / (fr1 * fr1 - 1.0)),
                1.0 / @as(f64, @sqrt(@abs(fr1 * fr1 - 1.0))),
            );
        }

        matrix.* = matrix.thenScale(@as(f64, @abs(1.0 - f_focal_x)));

        return data;
    }

    /// Whether the focal is on the circle.
    pub fn isFocalOnCircle(self: FocalData) bool {
        return math.isNearlyZero(1.0 - self.fr1);
    }

    /// Whether the focal points have been swapped.
    pub fn isSwapped(self: FocalData) bool {
        return self.f_is_swapped;
    }

    /// Whether the gradient is well-behaved.
    pub fn isWellBehaved(self: FocalData) bool {
        return !self.isFocalOnCircle() and self.fr1 > 1.0;
    }

    /// Whether the gradient is natively focal.
    pub fn isNativelyFocal(self: FocalData) bool {
        return math.isNearlyZero(self.f_focal_x);
    }
};

/// A radial gradient kind.
pub const RadialKind = union(enum) {
    /// The start and end center points are the same.
    radial: Radial,
    /// The start and end radius are the same.
    strip: Strip,
    /// A general, two-point conical gradient.
    focal: Focal,

    /// Same-center radial gradient (Skia `bias`/`scale`).
    pub const Radial = struct {
        /// Correction factor for a focal center that might not lie on the
        /// inner circle (if `r0 > 0`).
        bias: f32,
        /// Scaling factor mapping from `r0` to `r1`.
        scale: f32,
    };

    /// Same-radius radial gradient (Skia `scaled_r0_squared`).
    pub const Strip = struct {
        /// The squared value of `scaled_r0` (from the Skia implementation).
        scaled_r0_squared: f32,
    };

    /// General two-point conical gradient.
    pub const Focal = struct {
        /// The focal data (from the Skia implementation).
        focal_data: FocalData,
        /// The `fp0` value (from the Skia implementation).
        fp0: f32,
        /// The `fp1` value (from the Skia implementation).
        fp1: f32,
    };

    /// Whether the gradient is undefined at any location.
    pub fn hasUndefined(self: RadialKind) bool {
        return switch (self) {
            .radial => false,
            .strip => true,
            .focal => |focal| !focal.focal_data.isWellBehaved(),
        };
    }
};

/// Computed properties of a sweep gradient.
pub const SweepKind = struct {
    /// The start angle of the sweep gradient.
    start_angle: f32,
    /// The inverse delta between start and end angle.
    inv_angle_delta: f32,
};

/// A kind of encoded gradient.
pub const EncodedKind = union(enum) {
    /// An encoded linear gradient.
    linear: LinearKind,
    /// An encoded radial gradient.
    radial: RadialKind,
    /// An encoded sweep gradient.
    sweep: SweepKind,

    /// Whether the gradient is undefined at any location.
    fn hasUndefined(self: EncodedKind) bool {
        return switch (self) {
            .radial => |radial_kind| radial_kind.hasUndefined(),
            else => false,
        };
    }
};

/// An encoded gradient.
pub const EncodedGradient = struct {
    /// The cache key for the gradient.
    cache_key: GradientCacheKey,
    /// The underlying kind of gradient.
    kind: EncodedKind,
    /// Whether the gradient can yield undefined `t` values at some locations.
    has_undefined: bool,
    /// A transform applied to the position of the first processed pixel.
    transform: Affine,
    /// How much to advance in the x/y direction for one step in the x direction.
    x_advance: Vec2,
    /// How much to advance in the x/y direction for one step in the y direction.
    y_advance: Vec2,
    /// The color ranges of the gradient.
    ranges: []GradientRange,
    /// The extend mode of the gradient.
    extend: Extend,
    /// Whether the gradient requires `source_over` compositing.
    may_have_transparency: bool,
    /// Lazily built u8 LUT (upstream `OnceCell<GradientLut<u8>>`).
    u8_lut: ?GradientLut(u8) = null,
    /// Lazily built f32 LUT (upstream `OnceCell<GradientLut<f32>>`).
    f32_lut: ?GradientLut(f32) = null,

    /// Get the lookup table for sampling u8-based gradient values, building it
    /// on first access.
    ///
    /// Divergence: upstream's `OnceCell::get_or_init` takes `&self` and panics
    /// on allocation failure; this port takes `*EncodedGradient` (single
    /// threaded; M4 adds synchronization) and propagates `error.OutOfMemory`.
    pub fn u8Lut(self: *EncodedGradient, allocator: std.mem.Allocator) std.mem.Allocator.Error!*const GradientLut(u8) {
        if (self.u8_lut == null) {
            self.u8_lut = try GradientLut(u8).init(allocator, self.ranges);
        }
        if (self.u8_lut) |*lut| return lut;
        unreachable;
    }

    /// Get the lookup table for sampling f32-based gradient values, building
    /// it on first access. See [`EncodedGradient.u8Lut`].
    pub fn f32Lut(self: *EncodedGradient, allocator: std.mem.Allocator) std.mem.Allocator.Error!*const GradientLut(f32) {
        if (self.f32_lut == null) {
            self.f32_lut = try GradientLut(f32).init(allocator, self.ranges);
        }
        if (self.f32_lut) |*lut| return lut;
        unreachable;
    }

    /// Release the range/stops allocations and any built LUTs.
    pub fn deinit(self: *EncodedGradient, allocator: std.mem.Allocator) void {
        self.cache_key.stops.deinit();
        allocator.free(self.ranges);
        if (self.u8_lut) |*lut| lut.deinit(allocator);
        if (self.f32_lut) |*lut| lut.deinit(allocator);
        self.* = undefined;
    }
};

/// Cache key for gradient color ramps based on color-affecting properties.
pub const GradientCacheKey = struct {
    /// The color stops (offsets + colors).
    stops: ColorStops,
    /// Color space used for interpolation.
    interpolation_cs: ColorSpaceTag,
    /// Hue direction used for interpolation.
    hue_direction: HueDirection,

    /// Release the owned stops copy.
    pub fn deinit(self: *GradientCacheKey) void {
        self.stops.deinit();
    }

    /// Upstream `BitEq`: compare the stops and enum tags bit-for-bit (NaN
    /// offsets/colors compare equal when their bit patterns match).
    pub fn bitEql(self: *const GradientCacheKey, other: *const GradientCacheKey) bool {
        if (self.interpolation_cs != other.interpolation_cs) return false;
        if (self.hue_direction != other.hue_direction) return false;
        if (self.stops.items.len != other.stops.items.len) return false;
        for (self.stops.items, other.stops.items) |a, b| {
            if (!f32BitEql(a.offset, b.offset)) return false;
            for (a.color.components, b.color.components) |x, y| {
                if (!f32BitEql(x, y)) return false;
            }
        }
        return true;
    }

    /// Upstream `BitHash`: hash the stop bit patterns and the enum tags.
    ///
    /// The byte format is not part of the rendering contract yet; it only
    /// needs to be stable and consistent with [`GradientCacheKey.bitEql`]
    /// once a gradient cache consumes it.
    pub fn hash(self: *const GradientCacheKey, hasher: anytype) void {
        const len: u64 = self.stops.items.len;
        hasher.update(std.mem.asBytes(&len));
        for (self.stops.items) |stop| {
            const offset_bits: u32 = @bitCast(stop.offset);
            hasher.update(std.mem.asBytes(&offset_bits));
            for (stop.color.components) |component| {
                const bits: u32 = @bitCast(component);
                hasher.update(std.mem.asBytes(&bits));
            }
        }
        const cs = self.interpolation_cs.toU8();
        hasher.update(std.mem.asBytes(&cs));
        const hue = self.hue_direction.toU8();
        hasher.update(std.mem.asBytes(&hue));
    }
};

fn f32BitEql(a: f32, b: f32) bool {
    return @as(u32, @bitCast(a)) == @as(u32, @bitCast(b));
}

/// An encoded range between two color stops.
pub const GradientRange = struct {
    /// The end value of the range.
    x1: f32,
    /// The bias to apply when interpolating the color (the start color).
    bias: [4]f32,
    /// The scale factors of the range: `bias + x * scale`.
    scale: [4]f32,
    /// The alpha space in which the interpolation was performed.
    interpolation_alpha_space: InterpolationAlphaSpace,
};

// ---------------------------------------------------------------------------
// Gradient lookup tables
// ---------------------------------------------------------------------------

/// The Zig face of upstream's `GradientLutExt` trait: the element type
/// selects the conversion.
pub fn GradientLutExt(comptime T: type) type {
    if (T != u8 and T != f32) {
        @compileError("GradientLut only supports u8 and f32, got " ++ @typeName(T));
    }
    return struct {
        /// The zero value (upstream `ZERO`).
        pub const ZERO: T = switch (T) {
            u8 => 0,
            f32 => 0.0,
            else => unreachable,
        };

        /// Convert from `f32x16` to `[T; 16]`.
        pub fn fromF32x16(color: F32x16) [16]T {
            return switch (T) {
                // `f32_to_u8(color * 255.0 + 0.5)`, with upstream's
                // non-FMA `mul_add` on the portable/baseline backends.
                u8 => util.f32ToU8(simd.mulAddUnfused(
                    color,
                    @as(F32x16, @splat(255.0)),
                    @as(F32x16, @splat(0.5)),
                )),
                f32 => color,
                else => unreachable,
            };
        }
    };
}

/// A lookup table for sampled gradient values.
pub fn GradientLut(comptime T: type) type {
    return struct {
        values: [][4]T,
        scale: f32,

        const Self = @This();
        const Ext = GradientLutExt(T);

        /// Create a new lookup table (upstream `new`).
        ///
        /// Upstream vectorizes the constructor through `simd.vectorize`; the
        /// port always runs the SIMD-width loop (the helpers in
        /// `src/simd/root.zig` lower to scalar code on fallback targets).
        pub fn init(allocator: std.mem.Allocator, ranges: []const GradientRange) std.mem.Allocator.Error!Self {
            const lut_size = determineLutSize(ranges);
            const values = try allocator.alloc([4]T, lut_size);
            errdefer allocator.free(values);

            const zero: [4]T = .{ Ext.ZERO, Ext.ZERO, Ext.ZERO, Ext.ZERO };
            @memset(values, zero);

            // Flat view of the LUT, matching upstream's
            // `bytemuck::cast_slice_mut::<[T; 4], T>`.
            const lut_flat: []T = @as([*]T, @ptrCast(values.ptr))[0 .. lut_size * 4];

            // Calculate how many indices are covered by each range.
            const scale: f32 = @as(f32, @floatFromInt(lut_size)) - 1.0;
            const inv_lut_scale: F32x4 = @splat(1.0 / scale);
            const add_factor: F32x4 = @as(F32x4, .{ 0.0, 1.0, 2.0, 3.0 }) * inv_lut_scale;

            var prev_idx: usize = 0;
            for (ranges) |range| {
                const max_idx: usize = @intFromFloat(
                    range.x1 * @as(f32, @floatFromInt(lut_size)),
                );

                const bias4 = simd.fromSlice(F32x4, &range.bias);
                const scale4 = simd.fromSlice(F32x4, &range.scale);
                const biases = simd.blockSplat(bias4, bias4, bias4, bias4);
                const scales = simd.blockSplat(scale4, scale4, scale4, scale4);

                var idx = prev_idx;
                while (idx < max_idx) : (idx += 4) {
                    const t_vals_4 = simd.mulAddUnfused(
                        @as(F32x4, @splat(@as(f32, @floatFromInt(idx)))),
                        inv_lut_scale,
                        add_factor,
                    );
                    const t_vals = simd.elementWiseSplat(t_vals_4);

                    var result = simd.mulAddUnfused(scales, t_vals, biases);
                    const alphas = simd.splat4thPerGroup(result);
                    // Premultiply colors, since interpolation happened in
                    // unpremultiplied space.
                    if (range.interpolation_alpha_space == .unpremultiplied) {
                        const color_lane_mask: simd.Mask(F32x16) = .{
                            true, true, true, false,
                            true, true, true, false,
                            true, true, true, false,
                            true, true, true, false,
                        };
                        result = simd.select(F32x16, color_lane_mask, result * alphas, alphas);
                    }

                    // Floating-point impreciseness can push values above 1 or
                    // RGB above alpha; clamp to prevent later overflow.
                    result = @min(@min(result, @as(F32x16, @splat(1.0))), alphas);
                    const rs = Ext.fromF32x16(result);

                    // We always compute 4 samples at a time, but a ramp does
                    // not necessarily start at a multiple of 4, so truncate.
                    const start = idx * 4;
                    const end = @min(idx + 4, lut_size) * 4;
                    @memcpy(lut_flat[start..end], rs[0 .. end - start]);
                }
                prev_idx = max_idx;
            }

            return .{ .values = values, .scale = scale };
        }

        /// Release the lookup table.
        pub fn deinit(self: *Self, allocator: std.mem.Allocator) void {
            allocator.free(self.values);
            self.* = undefined;
        }

        /// Get the sample value at a specific index.
        pub fn get(self: *const Self, idx: usize) [4]T {
            return self.values[idx];
        }

        /// Return the raw array of gradient sample values.
        pub fn lut(self: *const Self) []const [4]T {
            return self.values;
        }

        /// Return the number of entries in the lookup table.
        pub fn width(self: *const Self) usize {
            return self.values.len;
        }

        /// Get the scale factor by which to scale the parametric value to
        /// compute the correct lookup index.
        pub fn scaleFactor(self: *const Self) f32 {
            return self.scale;
        }
    };
}

/// Determine the lookup table size for a set of ranges.
///
/// Inspired by Blend2D: 256 entries for one range, 512 for two, 1024 for more.
/// Tiny offsets increase the resolution, clamped to `MAX_GRADIENT_LUT_SIZE`.
fn determineLutSize(ranges: []const GradientRange) usize {
    const stop_len: usize = switch (ranges.len) {
        1 => 256,
        2 => 512,
        else => 1024,
    };

    var last_x1: f32 = 0.0;
    var min_size: usize = 0;

    for (ranges) |range| {
        const x1 = range.x1;
        // For example, if the first stop is at 0.001, we need a resolution of
        // at least 1000 to safely capture it.
        const res = @min(ceilToUsizeSat(1.0 / (x1 - last_x1)), MAX_GRADIENT_LUT_SIZE);
        const next_pow2: usize = if (res == 0) 1 else std.math.ceilPowerOfTwoAssert(usize, res);
        min_size = @max(min_size, next_pow2);
        last_x1 = x1;
    }

    // Take the maximum of both, but don't exceed the maximum size.
    return @max(stop_len, min_size);
}

/// Rust's `f32 as usize` saturating cast of an already-ceiled value, with the
/// `MAX_GRADIENT_LUT_SIZE` clamp applied. The clamp is equivalent to
/// upstream's trailing `.min(MAX_GRADIENT_LUT_SIZE)` because the following
/// `next_power_of_two` cannot leave the clamped range (4096 is a power of two).
fn ceilToUsizeSat(value: f32) usize {
    const ceiled = @ceil(value);
    if (std.math.isNan(ceiled) or ceiled <= 0.0) return 0;
    if (ceiled >= @as(f32, @floatFromInt(MAX_GRADIENT_LUT_SIZE))) {
        return MAX_GRADIENT_LUT_SIZE;
    }
    return @intFromFloat(ceiled);
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

const testing = std.testing;

/// Compare an encoded paint against a fallback solid color.
fn expectFallbackPaint(paint: Paint, expected: Color) !void {
    switch (paint) {
        .solid => |solid| try testing.expectEqualDeep(PremulColor.fromAlphaColor(expected), solid),
        .indexed => return error.TestUnexpectedResult,
    }
}

/// Release every encoded paint and the list itself.
fn drainPaints(paints: *std.ArrayList(EncodedPaint), allocator: std.mem.Allocator) void {
    for (paints.items) |*paint| paint.deinit(allocator);
    paints.deinit(allocator);
}

/// Build a gradient with copied stops.
fn makeGradient(allocator: std.mem.Allocator, kind: peniko.GradientKind, stops: []const ColorStop) !Gradient {
    return (Gradient{ .kind = kind }).withStops(allocator, stops);
}

/// The `EncodedGradient` a paint index refers to.
fn encodedGradientOf(paints: *std.ArrayList(EncodedPaint), paint: Paint) *EncodedGradient {
    return &paints.items[paint.indexed.index()].gradient;
}

test "gradient empty stops fall back to black (upstream gradient_missing_stops)" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer paints.deinit(allocator);

    const gradient = Gradient.newLinear(Point.new(0.0, 0.0), Point.new(20.0, 0.0));
    const paint = try encodeGradient(&gradient, allocator, &paints, Affine.IDENTITY, null);
    try expectFallbackPaint(paint, peniko.palette.css.BLACK);
    try testing.expectEqual(@as(usize, 0), paints.items.len);
}

test "gradient with one stop falls back to its color (upstream gradient_one_stop)" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer paints.deinit(allocator);

    const stops = [_]ColorStop{ColorStop.init(0.0, peniko.palette.css.GREEN)};
    var gradient = try makeGradient(
        allocator,
        .{ .linear = peniko.LinearGradientPosition.new(Point.new(0.0, 0.0), Point.new(20.0, 0.0)) },
        &stops,
    );
    defer gradient.deinit();

    const paint = try encodeGradient(&gradient, allocator, &paints, Affine.IDENTITY, null);
    try expectFallbackPaint(paint, peniko.palette.css.GREEN);
    try testing.expectEqual(@as(usize, 0), paints.items.len);
}

test "gradient with unsorted stops falls back to first color (upstream gradient_not_sorted_stops)" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer paints.deinit(allocator);

    const stops = [_]ColorStop{
        ColorStop.init(1.0, peniko.palette.css.GREEN),
        ColorStop.init(0.0, peniko.palette.css.BLUE),
    };
    var gradient = try makeGradient(
        allocator,
        .{ .linear = peniko.LinearGradientPosition.new(Point.new(0.0, 0.0), Point.new(20.0, 0.0)) },
        &stops,
    );
    defer gradient.deinit();

    const paint = try encodeGradient(&gradient, allocator, &paints, Affine.IDENTITY, null);
    try expectFallbackPaint(paint, peniko.palette.css.GREEN);
}

test "degenerate linear gradient falls back to first color (upstream gradient_linear_degenerate)" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer paints.deinit(allocator);

    const stops = [_]ColorStop{
        ColorStop.init(0.0, peniko.palette.css.GREEN),
        ColorStop.init(1.0, peniko.palette.css.BLUE),
    };
    var gradient = try makeGradient(
        allocator,
        .{ .linear = peniko.LinearGradientPosition.new(Point.new(0.0, 0.0), Point.new(0.0, 0.0)) },
        &stops,
    );
    defer gradient.deinit();

    const paint = try encodeGradient(&gradient, allocator, &paints, Affine.IDENTITY, null);
    try expectFallbackPaint(paint, peniko.palette.css.GREEN);
}

test "last stop with infinite offset is invalid (upstream gradient_last_stop_with_infinity_offset)" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer paints.deinit(allocator);

    const stops = [_]ColorStop{
        ColorStop.init(0.0, peniko.palette.css.GREEN),
        ColorStop.init(std.math.inf(f32), peniko.palette.css.BLUE),
    };
    var gradient = try makeGradient(
        allocator,
        .{ .linear = peniko.LinearGradientPosition.new(Point.new(0.0, 0.0), Point.new(20.0, 0.0)) },
        &stops,
    );
    defer gradient.deinit();

    const paint = try encodeGradient(&gradient, allocator, &paints, Affine.IDENTITY, null);
    try expectFallbackPaint(paint, peniko.palette.css.GREEN);
}

test "stop with NaN offset is invalid (upstream gradient_stop_with_nan_offset)" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer paints.deinit(allocator);

    const stops = [_]ColorStop{
        ColorStop.init(0.0, peniko.palette.css.GREEN),
        ColorStop.init(std.math.nan(f32), peniko.palette.css.BLUE),
    };
    var gradient = try makeGradient(
        allocator,
        .{ .linear = peniko.LinearGradientPosition.new(Point.new(0.0, 0.0), Point.new(20.0, 0.0)) },
        &stops,
    );
    defer gradient.deinit();

    const paint = try encodeGradient(&gradient, allocator, &paints, Affine.IDENTITY, null);
    try expectFallbackPaint(paint, peniko.palette.css.GREEN);
}

test "degenerate radial gradient falls back to first color (upstream gradient_radial_degenerate)" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer paints.deinit(allocator);

    const stops = [_]ColorStop{
        ColorStop.init(0.0, peniko.palette.css.GREEN),
        ColorStop.init(1.0, peniko.palette.css.BLUE),
    };
    var gradient = try makeGradient(
        allocator,
        .{ .radial = peniko.RadialGradientPosition.newTwoPoint(
            Point.new(0.0, 0.0),
            20.0,
            Point.new(0.0, 0.0),
            20.0,
        ) },
        &stops,
    );
    defer gradient.deinit();

    const paint = try encodeGradient(&gradient, allocator, &paints, Affine.IDENTITY, null);
    try expectFallbackPaint(paint, peniko.palette.css.GREEN);
}

test "negative radius falls back to first color" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer paints.deinit(allocator);

    const stops = [_]ColorStop{
        ColorStop.init(0.0, peniko.palette.css.GREEN),
        ColorStop.init(1.0, peniko.palette.css.BLUE),
    };
    var gradient = try makeGradient(
        allocator,
        .{ .radial = peniko.RadialGradientPosition.newTwoPoint(
            Point.new(0.0, 0.0),
            -2.0,
            Point.new(10.0, 0.0),
            4.0,
        ) },
        &stops,
    );
    defer gradient.deinit();

    const paint = try encodeGradient(&gradient, allocator, &paints, Affine.IDENTITY, null);
    try expectFallbackPaint(paint, peniko.palette.css.GREEN);
}

test "degenerate sweep gradient falls back to first color" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer paints.deinit(allocator);

    const stops = [_]ColorStop{
        ColorStop.init(0.0, peniko.palette.css.GREEN),
        ColorStop.init(1.0, peniko.palette.css.BLUE),
    };
    // Equal angles and a reversed (end < start) sweep are both invalid.
    inline for (.{ 0.5, 0.25 }) |end_angle| {
        var gradient = try makeGradient(
            allocator,
            .{ .sweep = peniko.SweepGradientPosition.new(Point.new(0.0, 0.0), 0.5, end_angle) },
            &stops,
        );
        defer gradient.deinit();
        const paint = try encodeGradient(&gradient, allocator, &paints, Affine.IDENTITY, null);
        try expectFallbackPaint(paint, peniko.palette.css.GREEN);
    }
}

test "linear gradient encode fields" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer drainPaints(&paints, allocator);

    const stops = [_]ColorStop{
        ColorStop.init(0.0, peniko.palette.css.GREEN),
        ColorStop.init(1.0, peniko.palette.css.BLUE),
    };
    var gradient = try makeGradient(
        allocator,
        .{ .linear = peniko.LinearGradientPosition.new(Point.new(0.0, 0.0), Point.new(20.0, 0.0)) },
        &stops,
    );
    defer gradient.deinit();

    const paint = try encodeGradient(&gradient, allocator, &paints, Affine.IDENTITY, null);
    try testing.expectEqual(@as(usize, 1), paints.items.len);
    const encoded = encodedGradientOf(&paints, paint);

    // The base transform maps (0, 0) -> (0, 0) and (20, 0) -> (1, 0).
    try testing.expectApproxEqAbs(@as(f64, 0.05), encoded.transform.c[0], 1e-15);
    try testing.expectApproxEqAbs(@as(f64, 0.0), encoded.transform.c[1], 1e-15);
    try testing.expectApproxEqAbs(@as(f64, 0.0), encoded.transform.c[2], 1e-15);
    try testing.expectApproxEqAbs(@as(f64, 0.05), encoded.transform.c[3], 1e-15);
    try testing.expectApproxEqAbs(@as(f64, 0.0), encoded.transform.transformPoint(Point.new(0.0, 0.0)).x, 1e-15);
    try testing.expectApproxEqAbs(@as(f64, 1.0), encoded.transform.transformPoint(Point.new(20.0, 0.0)).x, 1e-15);

    try testing.expectApproxEqAbs(@as(f64, 0.05), encoded.x_advance.x, 1e-15);
    try testing.expectApproxEqAbs(@as(f64, 0.0), encoded.x_advance.y, 1e-15);
    try testing.expectApproxEqAbs(@as(f64, 0.0), encoded.y_advance.x, 1e-15);
    try testing.expectApproxEqAbs(@as(f64, 0.05), encoded.y_advance.y, 1e-15);

    try testing.expect(encoded.kind == .linear);
    try testing.expect(!encoded.kind.hasUndefined());
    try testing.expect(!encoded.has_undefined);
    try testing.expectEqual(Extend.pad, encoded.extend);
    try testing.expect(!encoded.may_have_transparency);
    try testing.expectEqual(@as(usize, 1), encoded.ranges.len);

    // Range: bias is premultiplied green, scale is blue - green.
    const green = peniko.palette.css.GREEN.premultiply().components;
    try testing.expectEqualSlices(f32, &green, &encoded.ranges[0].bias);
    try testing.expectApproxEqAbs(@as(f32, 1.0), encoded.ranges[0].x1, 0.0);
    try testing.expectEqual(
        InterpolationAlphaSpace.premultiplied,
        encoded.ranges[0].interpolation_alpha_space,
    );

    // Cache key keeps the original stops and interpolation settings.
    try testing.expectEqual(@as(usize, 2), encoded.cache_key.stops.len());
    try testing.expectEqual(ColorSpaceTag.srgb, encoded.cache_key.interpolation_cs);
}

test "linear gradient with missing offsets pads ranges" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer drainPaints(&paints, allocator);

    const stops = [_]ColorStop{
        ColorStop.init(0.25, peniko.palette.css.GREEN),
        ColorStop.init(0.75, peniko.palette.css.BLUE),
    };
    var gradient = try makeGradient(
        allocator,
        .{ .linear = peniko.LinearGradientPosition.new(Point.new(0.0, 0.0), Point.new(1.0, 0.0)) },
        &stops,
    );
    defer gradient.deinit();

    const paint = try encodeGradient(&gradient, allocator, &paints, Affine.IDENTITY, null);
    const encoded = encodedGradientOf(&paints, paint);

    // Three ranges: 0 -> 0.25 -> 0.75 -> 1.
    try testing.expectEqual(@as(usize, 3), encoded.ranges.len);
    try testing.expectApproxEqAbs(@as(f32, 0.25), encoded.ranges[0].x1, 0.0);
    try testing.expectApproxEqAbs(@as(f32, 0.75), encoded.ranges[1].x1, 0.0);
    try testing.expectApproxEqAbs(@as(f32, 1.0), encoded.ranges[2].x1, 0.0);

    // The padded first range starts at the green stop; its bias is green.
    try testing.expectEqualSlices(
        f32,
        &peniko.palette.css.GREEN.premultiply().components,
        &encoded.ranges[0].bias,
    );
    // The cache key keeps only the two original stops.
    try testing.expectEqual(@as(usize, 2), encoded.cache_key.stops.len());
}

test "gradient ranges use premultiplied colors unless unpremultiplied" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer drainPaints(&paints, allocator);

    const stops = [_]ColorStop{
        ColorStop.init(0.0, Color.new(.{ 0.5, 0.2, 0.1, 0.5 })),
        ColorStop.init(1.0, Color.new(.{ 0.2, 0.4, 0.6, 1.0 })),
    };

    var gradient = try makeGradient(
        allocator,
        .{ .linear = peniko.LinearGradientPosition.new(Point.new(0.0, 0.0), Point.new(1.0, 0.0)) },
        &stops,
    );
    defer gradient.deinit();

    var unpremultiplied = try makeGradient(
        allocator,
        .{ .linear = peniko.LinearGradientPosition.new(Point.new(0.0, 0.0), Point.new(1.0, 0.0)) },
        &stops,
    );
    unpremultiplied = unpremultiplied.withInterpolationAlphaSpace(.unpremultiplied);
    defer unpremultiplied.deinit();

    const premul_paint = try encodeGradient(&gradient, allocator, &paints, Affine.IDENTITY, null);
    const premul = encodedGradientOf(&paints, premul_paint);
    try testing.expectEqualSlices(f32, &.{ 0.25, 0.1, 0.05, 0.5 }, &premul.ranges[0].bias);
    try testing.expectEqual(InterpolationAlphaSpace.premultiplied, premul.ranges[0].interpolation_alpha_space);

    const straight_paint = try encodeGradient(&unpremultiplied, allocator, &paints, Affine.IDENTITY, null);
    const straight = encodedGradientOf(&paints, straight_paint);
    try testing.expectEqualSlices(f32, &.{ 0.5, 0.2, 0.1, 0.5 }, &straight.ranges[0].bias);
    try testing.expectEqual(InterpolationAlphaSpace.unpremultiplied, straight.ranges[0].interpolation_alpha_space);
}

test "radial same-center gradient encode fields" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer drainPaints(&paints, allocator);

    const stops = [_]ColorStop{
        ColorStop.init(0.0, peniko.palette.css.GREEN),
        ColorStop.init(1.0, peniko.palette.css.BLUE),
    };
    var gradient = try makeGradient(
        allocator,
        .{ .radial = peniko.RadialGradientPosition.newTwoPoint(
            Point.new(3.0, 4.0),
            0.0,
            Point.new(3.0, 4.0),
            10.0,
        ) },
        &stops,
    );
    defer gradient.deinit();

    const paint = try encodeGradient(&gradient, allocator, &paints, Affine.IDENTITY, null);
    const encoded = encodedGradientOf(&paints, paint);

    try testing.expect(encoded.kind == .radial);
    const radial = encoded.kind.radial;
    try testing.expect(radial == .radial);
    try testing.expectApproxEqAbs(@as(f32, 0.0), radial.radial.bias, 0.0);
    try testing.expectApproxEqAbs(@as(f32, 1.0), radial.radial.scale, 0.0);
    try testing.expect(!radial.hasUndefined());
    try testing.expect(!encoded.has_undefined);
    try testing.expect(!encoded.may_have_transparency);

    // Center moved to the origin, then scaled by 1 / max(r0, r1).
    const moved = encoded.transform.transformPoint(Point.new(3.0, 4.0));
    try testing.expectApproxEqAbs(@as(f64, 0.0), moved.x, 1e-15);
    try testing.expectApproxEqAbs(@as(f64, 0.0), moved.y, 1e-15);
    try testing.expectApproxEqAbs(@as(f64, 0.1), encoded.x_advance.x, 1e-15);
    try testing.expectApproxEqAbs(@as(f64, 0.1), encoded.y_advance.y, 1e-15);
}

test "radial same-radius gradient produces an undefined strip" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer drainPaints(&paints, allocator);

    const stops = [_]ColorStop{
        ColorStop.init(0.0, peniko.palette.css.GREEN),
        ColorStop.init(1.0, peniko.palette.css.BLUE),
    };
    var gradient = try makeGradient(
        allocator,
        .{ .radial = peniko.RadialGradientPosition.newTwoPoint(
            Point.new(0.0, 0.0),
            5.0,
            Point.new(8.0, 0.0),
            5.0,
        ) },
        &stops,
    );
    defer gradient.deinit();

    const paint = try encodeGradient(&gradient, allocator, &paints, Affine.IDENTITY, null);
    const encoded = encodedGradientOf(&paints, paint);

    try testing.expect(encoded.kind.radial == .strip);
    const strip = encoded.kind.radial.strip;
    // scaled_r0 = r1 / distance = 5 / 8.
    const expected = (5.0 / 8.0) * (5.0 / 8.0);
    try testing.expectApproxEqAbs(expected, strip.scaled_r0_squared, 1e-7);
    try testing.expect(encoded.kind.radial.hasUndefined());
    try testing.expect(encoded.has_undefined);
    // Undefined positions render as transparent, so compositing is required.
    try testing.expect(encoded.may_have_transparency);
}

test "radial two-point gradient produces focal data" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer drainPaints(&paints, allocator);

    const stops = [_]ColorStop{
        ColorStop.init(0.0, peniko.palette.css.GREEN),
        ColorStop.init(1.0, peniko.palette.css.BLUE),
    };
    var gradient = try makeGradient(
        allocator,
        .{ .radial = peniko.RadialGradientPosition.newTwoPoint(
            Point.new(0.0, 0.0),
            0.5,
            Point.new(2.0, 0.0),
            3.0,
        ) },
        &stops,
    );
    defer gradient.deinit();

    const paint = try encodeGradient(&gradient, allocator, &paints, Affine.IDENTITY, null);
    const encoded = encodedGradientOf(&paints, paint);

    try testing.expect(encoded.kind.radial == .focal);
    const focal = encoded.kind.radial.focal;
    // r0 / d = 0.25, r1 / d = 1.5 -> f = 0.25 / (0.25 - 1.5) = -0.2,
    // fr1 = 1.5 / |1 - (-0.2)| = 1.25.
    try testing.expectApproxEqAbs(@as(f32, -0.2), focal.focal_data.f_focal_x, 1e-6);
    try testing.expectApproxEqAbs(@as(f32, 1.25), focal.focal_data.fr1, 1e-6);
    try testing.expectApproxEqAbs(@as(f32, 0.8), focal.fp0, 1e-6);
    try testing.expectApproxEqAbs(@as(f32, -0.2), focal.fp1, 1e-6);
    try testing.expect(focal.focal_data.isWellBehaved());
    try testing.expect(!focal.focal_data.isFocalOnCircle());
    try testing.expect(!focal.focal_data.isNativelyFocal());
    try testing.expect(!encoded.has_undefined);
}

test "radial focal-on-circle gradient has undefined positions" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer drainPaints(&paints, allocator);

    const stops = [_]ColorStop{
        ColorStop.init(0.0, peniko.palette.css.GREEN),
        ColorStop.init(1.0, peniko.palette.css.BLUE),
    };
    // r0 = d, r1 = 2d -> fr1 == 1 (focal on circle).
    var gradient = try makeGradient(
        allocator,
        .{ .radial = peniko.RadialGradientPosition.newTwoPoint(
            Point.new(0.0, 0.0),
            2.0,
            Point.new(2.0, 0.0),
            4.0,
        ) },
        &stops,
    );
    defer gradient.deinit();

    const paint = try encodeGradient(&gradient, allocator, &paints, Affine.IDENTITY, null);
    const encoded = encodedGradientOf(&paints, paint);
    const focal = encoded.kind.radial.focal;
    try testing.expect(focal.focal_data.isFocalOnCircle());
    try testing.expect(!focal.focal_data.isWellBehaved());
    try testing.expect(encoded.has_undefined);
    try testing.expect(encoded.may_have_transparency);
}

test "focal data swaps focal points on the circle" {
    var matrix = Affine.IDENTITY;
    // r1 / r0 is below the near-zero tolerance, so f_focal_x is nearly 1 and
    // the focal point is swapped with a mirrored matrix.
    const data = FocalData.create(1.0, 1.0e-9, &matrix);
    try testing.expect(data.isSwapped());
    try testing.expectEqual(@as(f32, 0.0), data.f_focal_x);
    try testing.expect(data.isFocalOnCircle());

    var native_matrix = Affine.IDENTITY;
    const native = FocalData.create(0.0, 1.0, &native_matrix);
    try testing.expect(native.isNativelyFocal());
    try testing.expect(!native.isSwapped());
    try testing.expectApproxEqAbs(@as(f32, 1.0), native.fr1, 0.0);
}

test "sweep gradient encode fields" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer drainPaints(&paints, allocator);

    const stops = [_]ColorStop{
        ColorStop.init(0.0, peniko.palette.css.GREEN),
        ColorStop.init(1.0, peniko.palette.css.BLUE),
    };
    var gradient = try makeGradient(
        allocator,
        .{ .sweep = peniko.SweepGradientPosition.new(Point.new(5.0, 7.0), 0.25, 1.5) },
        &stops,
    );
    defer gradient.deinit();

    const paint = try encodeGradient(&gradient, allocator, &paints, Affine.IDENTITY, null);
    const encoded = encodedGradientOf(&paints, paint);

    try testing.expect(encoded.kind == .sweep);
    try testing.expectApproxEqAbs(@as(f32, 0.25), encoded.kind.sweep.start_angle, 0.0);
    try testing.expectApproxEqAbs(@as(f32, 0.8), encoded.kind.sweep.inv_angle_delta, 1e-7);
    try testing.expect(!encoded.has_undefined);

    // The center is translated to the origin.
    const moved = encoded.transform.transformPoint(Point.new(5.0, 7.0));
    try testing.expectApproxEqAbs(@as(f64, 0.0), moved.x, 0.0);
    try testing.expectApproxEqAbs(@as(f64, 0.0), moved.y, 0.0);
    try testing.expectApproxEqAbs(@as(f64, 1.0), encoded.x_advance.x, 1e-15);
    try testing.expectApproxEqAbs(@as(f64, 1.0), encoded.y_advance.y, 1e-15);
}

test "non-sRGB gradient interpolation is unsupported" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer drainPaints(&paints, allocator);

    const stops = [_]ColorStop{
        ColorStop.init(0.0, peniko.palette.css.GREEN),
        ColorStop.init(1.0, peniko.palette.css.BLUE),
    };
    var gradient = (try makeGradient(
        allocator,
        .{ .linear = peniko.LinearGradientPosition.new(Point.new(0.0, 0.0), Point.new(1.0, 0.0)) },
        &stops,
    )).withInterpolationCs(.oklab);
    defer gradient.deinit();

    try testing.expectError(
        error.Unsupported,
        encodeGradient(&gradient, allocator, &paints, Affine.IDENTITY, null),
    );
    try testing.expectEqual(@as(usize, 0), paints.items.len);
}

test "gradient cache key bit equality and hashing" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer drainPaints(&paints, allocator);

    const stops = [_]ColorStop{
        ColorStop.init(0.0, peniko.palette.css.GREEN),
        ColorStop.init(1.0, peniko.palette.css.BLUE),
    };
    var a = try makeGradient(
        allocator,
        .{ .linear = peniko.LinearGradientPosition.new(Point.new(0.0, 0.0), Point.new(1.0, 0.0)) },
        &stops,
    );
    defer a.deinit();
    var b = try makeGradient(
        allocator,
        .{ .linear = peniko.LinearGradientPosition.new(Point.new(0.0, 0.0), Point.new(1.0, 0.0)) },
        &stops,
    );
    defer b.deinit();
    var c = (try makeGradient(
        allocator,
        .{ .linear = peniko.LinearGradientPosition.new(Point.new(0.0, 0.0), Point.new(1.0, 0.0)) },
        &stops,
    )).withHueDirection(.longer);
    defer c.deinit();

    const paint_a = try encodeGradient(&a, allocator, &paints, Affine.IDENTITY, null);
    const paint_b = try encodeGradient(&b, allocator, &paints, Affine.IDENTITY, null);
    const paint_c = try encodeGradient(&c, allocator, &paints, Affine.IDENTITY, null);
    const key_a = &encodedGradientOf(&paints, paint_a).cache_key;
    const key_b = &encodedGradientOf(&paints, paint_b).cache_key;
    const key_c = &encodedGradientOf(&paints, paint_c).cache_key;

    try testing.expect(key_a.bitEql(key_b));
    try testing.expect(!key_a.bitEql(key_c));

    var hash_a = std.hash.Wyhash.init(0);
    var hash_b = std.hash.Wyhash.init(0);
    var hash_c = std.hash.Wyhash.init(0);
    key_a.hash(&hash_a);
    key_b.hash(&hash_b);
    key_c.hash(&hash_c);
    try testing.expectEqual(hash_a.final(), hash_b.final());
    try testing.expect(hash_a.final() != hash_c.final());
}

test "determine_lut_size stop counts, gaps, and cap" {
    const one = [_]GradientRange{syntheticRange(1.0)};
    try testing.expectEqual(@as(usize, 256), determineLutSize(&one));

    const two = [_]GradientRange{ syntheticRange(0.5), syntheticRange(1.0) };
    try testing.expectEqual(@as(usize, 512), determineLutSize(&two));

    const three = [_]GradientRange{ syntheticRange(0.25), syntheticRange(0.5), syntheticRange(1.0) };
    try testing.expectEqual(@as(usize, 1024), determineLutSize(&three));

    // A tiny first gap raises the resolution beyond the stop-count default.
    const tiny_gap = [_]GradientRange{ syntheticRange(0.001), syntheticRange(1.0) };
    try testing.expectEqual(@as(usize, 1024), determineLutSize(&tiny_gap));

    // 1 / 4096 is exactly representable; one more octave is capped at 4096.
    const exact_pow2 = [_]GradientRange{ syntheticRange(1.0 / 4096.0), syntheticRange(1.0) };
    try testing.expectEqual(@as(usize, 4096), determineLutSize(&exact_pow2));

    const tiny = [_]GradientRange{ syntheticRange(0.0001), syntheticRange(1.0) };
    try testing.expectEqual(@as(usize, MAX_GRADIENT_LUT_SIZE), determineLutSize(&tiny));

    // Duplicate offsets make the divisor zero (infinite resolution), capped.
    const duplicate = [_]GradientRange{ syntheticRange(0.5), syntheticRange(0.5), syntheticRange(1.0) };
    try testing.expectEqual(@as(usize, MAX_GRADIENT_LUT_SIZE), determineLutSize(&duplicate));
}

fn syntheticRange(x1: f32) GradientRange {
    return .{
        .x1 = x1,
        .bias = .{ 0.0, 0.0, 0.0, 0.0 },
        .scale = .{ 0.0, 0.0, 0.0, 0.0 },
        .interpolation_alpha_space = .premultiplied,
    };
}

/// The x86 `cvttps2dq`-then-low-byte conversion `util.f32ToU8` documents,
/// written out so the reference LUT does not call the implementation.
fn referenceConvertU8(x: f32) u8 {
    if (std.math.isNan(x)) return 0;
    const truncated = @trunc(x);
    if (truncated >= 2147483648.0 or truncated < -2147483648.0) return 0;
    const as_i32: i32 = @intFromFloat(truncated);
    return @truncate(@as(u32, @bitCast(as_i32)));
}

/// Independent scalar transcription of the documented LUT math:
/// `bias + x * scale` with upstream's unfused `mul_add`, the
/// unpremultiplied fixup, and `min(1.0).min(alpha)` clamping.
fn referenceLut(
    comptime T: type,
    allocator: std.mem.Allocator,
    ranges: []const GradientRange,
) ![]T {
    const lut_size = determineLutSize(ranges);
    const out = try allocator.alloc(T, lut_size * 4);
    errdefer allocator.free(out);

    const scale: f32 = @as(f32, @floatFromInt(lut_size)) - 1.0;
    const inv_lut_scale: f32 = 1.0 / scale;

    var prev_idx: usize = 0;
    for (ranges) |range| {
        const max_idx: usize = @intFromFloat(range.x1 * @as(f32, @floatFromInt(lut_size)));
        var idx = prev_idx;
        while (idx < max_idx) : (idx += 4) {
            const base_t = @as(f32, @floatFromInt(idx)) * inv_lut_scale;
            var block: [16]T = undefined;
            // The last block of a table can be truncated; only the copied
            // lanes are part of the reference.
            const lanes_in_block = @min(idx + 4, lut_size) - idx;
            for (0..lanes_in_block) |lane| {
                const t = base_t + @as(f32, @floatFromInt(lane)) * inv_lut_scale;
                var pixel: [4]f32 = undefined;
                for (0..4) |channel| {
                    pixel[channel] = range.scale[channel] * t + range.bias[channel];
                }
                const alpha = pixel[3];
                if (range.interpolation_alpha_space == .unpremultiplied) {
                    pixel[0] = pixel[0] * alpha;
                    pixel[1] = pixel[1] * alpha;
                    pixel[2] = pixel[2] * alpha;
                }
                for (0..4) |channel| {
                    const clamped = @min(@min(pixel[channel], 1.0), alpha);
                    block[lane * 4 + channel] = if (T == u8)
                        referenceConvertU8(clamped * 255.0 + 0.5)
                    else
                        clamped;
                }
            }
            const start = idx * 4;
            const end = @min(idx + 4, lut_size) * 4;
            @memcpy(out[start..end], block[0 .. end - start]);
        }
        prev_idx = max_idx;
    }

    return out;
}

test "LUT bytes match an independent scalar computation" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer drainPaints(&paints, allocator);

    const opaque_stops = [_]ColorStop{
        ColorStop.init(0.0, peniko.palette.css.RED),
        ColorStop.init(0.5, peniko.palette.css.GREEN),
        ColorStop.init(1.0, peniko.palette.css.BLUE),
    };
    const translucent_stops = [_]ColorStop{
        ColorStop.init(0.0, Color.new(.{ 1.0, 0.0, 0.0, 0.25 })),
        ColorStop.init(0.1, Color.new(.{ 0.0, 1.0, 0.0, 0.5 })),
        ColorStop.init(1.0, Color.new(.{ 0.0, 0.0, 1.0, 1.0 })),
    };
    const padded_stops = [_]ColorStop{
        ColorStop.init(0.25, peniko.palette.css.RED),
        ColorStop.init(0.75, Color.new(.{ 0.0, 0.0, 1.0, 0.5 })),
    };
    const tiny_gap_stops = [_]ColorStop{
        ColorStop.init(0.0, peniko.palette.css.RED),
        ColorStop.init(0.001, Color.new(.{ 0.0, 1.0, 0.0, 0.5 })),
        ColorStop.init(1.0, peniko.palette.css.BLUE),
    };

    // (stops, alpha space) pairs; stop slices must outlive the loop.
    const cases = [_]struct { stops: []const ColorStop, alpha_space: InterpolationAlphaSpace }{
        .{ .stops = &opaque_stops, .alpha_space = .premultiplied },
        .{ .stops = &translucent_stops, .alpha_space = .premultiplied },
        .{ .stops = &translucent_stops, .alpha_space = .unpremultiplied },
        .{ .stops = &padded_stops, .alpha_space = .premultiplied },
        .{ .stops = &tiny_gap_stops, .alpha_space = .premultiplied },
    };

    for (cases) |case| {
        var gradient = try makeGradient(
            allocator,
            .{ .linear = peniko.LinearGradientPosition.new(Point.new(0.0, 0.0), Point.new(10.0, 0.0)) },
            case.stops,
        );
        defer gradient.deinit();
        gradient = gradient.withInterpolationAlphaSpace(case.alpha_space);

        const paint = try encodeGradient(&gradient, allocator, &paints, Affine.IDENTITY, null);
        const encoded = encodedGradientOf(&paints, paint);

        const u8_lut = try encoded.u8Lut(allocator);
        const expected_u8 = try referenceLut(u8, allocator, encoded.ranges);
        defer allocator.free(expected_u8);
        try testing.expectEqual(expected_u8.len, u8_lut.width() * 4);
        try testing.expectEqualSlices(u8, expected_u8, std.mem.sliceAsBytes(u8_lut.lut()));
        try testing.expectEqual(
            @as(f32, @floatFromInt(u8_lut.width())) - 1.0,
            u8_lut.scaleFactor(),
        );

        const f32_lut = try encoded.f32Lut(allocator);
        const expected_f32 = try referenceLut(f32, allocator, encoded.ranges);
        defer allocator.free(expected_f32);
        try testing.expectEqual(expected_f32.len, f32_lut.width() * 4);
        try testing.expectEqualSlices(
            f32,
            expected_f32,
            std.mem.bytesAsSlice(f32, std.mem.sliceAsBytes(f32_lut.lut())),
        );

        // The LUT is built once and reused.
        try testing.expectEqual(u8_lut, try encoded.u8Lut(allocator));
    }
}

test "u8 lut clamps min(1.0).min(alpha)" {
    const allocator = testing.allocator;
    // bias RGB deliberately exceeds 1 and exceeds alpha; scale is zero so
    // every index has the same value.
    const ranges = [_]GradientRange{.{
        .x1 = 1.0,
        .bias = .{ 2.0, 0.5, 0.9, 0.8 },
        .scale = .{ 0.0, 0.0, 0.0, 0.0 },
        .interpolation_alpha_space = .premultiplied,
    }};

    var lut = try GradientLut(u8).init(allocator, &ranges);
    defer lut.deinit(allocator);

    try testing.expectEqual(@as(usize, 256), lut.width());
    const expected = [4]u8{ 204, 128, 204, 204 };
    for ([_]usize{ 0, 1, 42, 255 }) |idx| {
        try testing.expectEqual(expected, lut.get(idx));
    }

    var f32_lut = try GradientLut(f32).init(allocator, &ranges);
    defer f32_lut.deinit(allocator);
    try testing.expectEqualDeep([4]f32{ 0.8, 0.5, 0.8, 0.8 }, f32_lut.get(0));
    try testing.expectEqualDeep([4]f32{ 0.8, 0.5, 0.8, 0.8 }, f32_lut.get(255));
}

test "u8 lut premultiplies unpremultiplied ranges" {
    const allocator = testing.allocator;
    const ranges = [_]GradientRange{.{
        .x1 = 1.0,
        .bias = .{ 1.0, 0.5, 0.0, 0.5 },
        .scale = .{ 0.0, 0.0, 0.0, 0.0 },
        .interpolation_alpha_space = .unpremultiplied,
    }};

    var lut = try GradientLut(u8).init(allocator, &ranges);
    defer lut.deinit(allocator);

    // [1.0, 0.5, 0.0, 0.5] * alpha -> [0.5, 0.25, 0.0, 0.5].
    const expected = [4]u8{ 128, 64, 0, 128 };
    try testing.expectEqual(expected, lut.get(0));
    try testing.expectEqual(expected, lut.get(255));
}

test "image sampler alpha folds into the tint (upstream image_sampler_alpha_with_tint)" {
    const allocator = testing.allocator;

    const image = Image{
        .image = ImageSource.initOpaqueIdWithTransparencyHint(paint_mod.ImageId.new(1), false),
        .sampler = ImageSampler{ .alpha = 0.5, .quality = .medium },
    };

    for ([_]TintMode{ .alpha_mask, .multiply }) |mode| {
        var paints: std.ArrayList(EncodedPaint) = .empty;
        defer drainPaints(&paints, allocator);

        const tint = Tint{ .color = Color.new(.{ 0.2, 0.4, 0.6, 0.8 }), .mode = mode };
        _ = try encodeImage(&image, allocator, &paints, Affine.IDENTITY, tint);

        const encoded = &paints.items[0].image;
        try testing.expectEqual(@as(f32, 1.0), encoded.sampler.alpha);
        const expected_tint = Tint{ .color = Color.new(.{ 0.2, 0.4, 0.6, 0.4 }), .mode = mode };
        try testing.expectEqualDeep(expected_tint, encoded.tint.?);
        try testing.expect(encoded.may_have_transparency);
    }
}

test "image sampler alpha fold is clamped (upstream image_sampler_alpha_with_tint_is_clamped)" {
    const allocator = testing.allocator;

    const image = Image{
        .image = ImageSource.initOpaqueIdWithTransparencyHint(paint_mod.ImageId.new(1), false),
        .sampler = ImageSampler{ .alpha = 2.0, .quality = .medium },
    };
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer drainPaints(&paints, allocator);

    const tint = Tint{ .color = Color.new(.{ 0.2, 0.4, 0.6, 0.8 }), .mode = .multiply };
    _ = try encodeImage(&image, allocator, &paints, Affine.IDENTITY, tint);

    const encoded = &paints.items[0].image;
    try testing.expectEqual(@as(f32, 1.0), encoded.sampler.alpha);
    try testing.expectEqualDeep(
        Tint{ .color = Color.new(.{ 0.2, 0.4, 0.6, 1.0 }), .mode = .multiply },
        encoded.tint.?,
    );
    try testing.expect(!encoded.may_have_transparency);
}

test "sampler alpha creates a white multiply tint when none is given" {
    const allocator = testing.allocator;

    const image = Image{
        .image = ImageSource.initOpaqueIdWithTransparencyHint(paint_mod.ImageId.new(2), true),
        .sampler = ImageSampler{ .alpha = 0.25, .quality = .medium },
    };
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer drainPaints(&paints, allocator);

    _ = try encodeImage(&image, allocator, &paints, Affine.IDENTITY, null);
    const encoded = &paints.items[0].image;
    try testing.expectEqualDeep(
        Tint{ .color = Color.WHITE.withAlpha(0.25), .mode = .multiply },
        encoded.tint.?,
    );
    try testing.expect(encoded.may_have_transparency);
}

test "integer translation downgrades image quality to low" {
    const allocator = testing.allocator;

    const image = Image{
        .image = ImageSource.initOpaqueIdWithTransparencyHint(paint_mod.ImageId.new(3), false),
        .sampler = ImageSampler{ .quality = .medium },
    };
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer drainPaints(&paints, allocator);

    _ = try encodeImage(
        &image,
        allocator,
        &paints,
        Affine.translate(Vec2.new(2.0, 3.0)),
        null,
    );
    try testing.expectEqual(ImageQuality.low, paints.items[0].image.sampler.quality);

    // Non-integer translations keep the requested quality.
    _ = try encodeImage(
        &image,
        allocator,
        &paints,
        Affine.translate(Vec2.new(2.5, 3.0)),
        null,
    );
    try testing.expectEqual(ImageQuality.medium, paints.items[1].image.sampler.quality);
}

test "encoded image transform and advances" {
    const allocator = testing.allocator;

    const image = Image{
        .image = ImageSource.initOpaqueIdWithTransparencyHint(paint_mod.ImageId.new(4), false),
        .sampler = ImageSampler{ .quality = .medium },
    };
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer drainPaints(&paints, allocator);

    const scale = Affine.scale(2.0);
    const paint = try encodeImage(&image, allocator, &paints, scale, null);
    const encoded = &paints.items[paint.indexed.index()].image;

    // The stored transform is the inverse of the paint transform.
    try testing.expectApproxEqAbs(@as(f64, 0.5), encoded.transform.c[0], 1e-15);
    try testing.expectApproxEqAbs(@as(f64, 0.5), encoded.transform.c[3], 1e-15);
    try testing.expectApproxEqAbs(@as(f64, 0.5), encoded.x_advance.x, 1e-15);
    try testing.expectApproxEqAbs(@as(f64, 0.5), encoded.y_advance.y, 1e-15);
    try testing.expect(encoded.tint == null);
    try testing.expect(!encoded.may_have_transparency);
}

test "mayHaveTransparency for encoded paints and the paint query" {
    const allocator = testing.allocator;

    const solid_opaque = Paint.fromAlphaColor(peniko.palette.css.WHITE);
    try testing.expect(!paintMayHaveTransparency(solid_opaque, &.{}));
    const solid_translucent = Paint.fromAlphaColor(Color.new(.{ 0.0, 0.0, 0.0, 0.5 }));
    try testing.expect(paintMayHaveTransparency(solid_translucent, &.{}));

    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer drainPaints(&paints, allocator);

    const stops = [_]ColorStop{
        ColorStop.init(0.0, peniko.palette.css.GREEN),
        ColorStop.init(1.0, Color.new(.{ 0.0, 0.0, 1.0, 0.5 })),
    };
    var gradient = try makeGradient(
        allocator,
        .{ .linear = peniko.LinearGradientPosition.new(Point.new(0.0, 0.0), Point.new(1.0, 0.0)) },
        &stops,
    );
    defer gradient.deinit();
    const gradient_paint = try encodeGradient(&gradient, allocator, &paints, Affine.IDENTITY, null);
    try testing.expect(paintMayHaveTransparency(gradient_paint, paints.items));

    const image = Image{
        .image = ImageSource.initOpaqueIdWithTransparencyHint(paint_mod.ImageId.new(5), false),
        .sampler = ImageSampler.default,
    };
    const image_paint = try encodeImage(&image, allocator, &paints, Affine.IDENTITY, null);
    try testing.expect(!paintMayHaveTransparency(image_paint, paints.items));

    // Blurred rounded rectangles are conservatively transparent.
    try testing.expect((EncodedPaint{ .blurred_rounded_rect = undefined }).mayHaveTransparency());
}

test "image source resolved through a no-op resolver keeps its transparency hint" {
    const allocator = testing.allocator;

    const resolver = paint_mod.NoOpImageResolver.imageResolver(.{});
    try testing.expect(resolver.resolve(paint_mod.ImageId.new(9)) == null);

    const opaque_image = Image{
        .image = ImageSource.initOpaqueIdWithTransparencyHint(paint_mod.ImageId.new(9), false),
        .sampler = ImageSampler.default,
    };
    const transparent_image = Image{
        .image = ImageSource.initOpaqueIdWithTransparencyHint(paint_mod.ImageId.new(9), true),
        .sampler = ImageSampler.default,
    };

    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer drainPaints(&paints, allocator);

    _ = try encodeImage(&opaque_image, allocator, &paints, Affine.IDENTITY, null);
    _ = try encodeImage(&transparent_image, allocator, &paints, Affine.IDENTITY, null);
    try testing.expect(!paints.items[0].image.may_have_transparency);
    try testing.expect(paints.items[1].image.may_have_transparency);
}

test "blurred rounded rectangle encoder is unsupported" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer paints.deinit(allocator);

    const rect = BlurredRoundedRectangle{
        .rect = kurbo.Rect.new(0.0, 0.0, 10.0, 10.0),
        .color = peniko.palette.css.RED,
        .radius = 2.0,
        .std_dev = 1.0,
        .invert = false,
    };
    try testing.expectError(
        error.Unsupported,
        encodeInto(rect, allocator, &paints, Affine.IDENTITY, null),
    );
    try testing.expectEqual(@as(usize, 0), paints.items.len);
}

test "encodeInto dispatches by value and by pointer" {
    const allocator = testing.allocator;
    var paints: std.ArrayList(EncodedPaint) = .empty;
    defer drainPaints(&paints, allocator);

    const stops = [_]ColorStop{
        ColorStop.init(0.0, peniko.palette.css.GREEN),
        ColorStop.init(1.0, peniko.palette.css.BLUE),
    };
    var gradient = try makeGradient(
        allocator,
        .{ .linear = peniko.LinearGradientPosition.new(Point.new(0.0, 0.0), Point.new(1.0, 0.0)) },
        &stops,
    );
    defer gradient.deinit();

    const by_pointer = try EncodeExt.encodeInto(&gradient, allocator, &paints, Affine.IDENTITY, null);
    const by_value = try encodeInto(gradient, allocator, &paints, Affine.IDENTITY, null);
    try testing.expect(by_pointer.indexed.index() == 0);
    try testing.expect(by_value.indexed.index() == 1);
    try testing.expectEqual(@as(usize, 2), paints.items.len);
}
