//! Dashboard data, mirrored from the shadcn `dashboard-01` block.
//!
//! Chart series are the 91 daily points (Apr 1 - Jun 30, 2024) from
//! `chart-area-interactive.tsx`; table rows come from its `data.json`.

/// One day of the "Total Visitors" chart.
#[derive(Clone, Copy)]
pub struct Day {
    pub label: &'static str,
    pub desktop: u32,
    pub mobile: u32,
}

impl Day {
    /// The stacked total, what the top area of the chart outlines.
    pub fn total(&self) -> u32 {
        self.desktop + self.mobile
    }
}

pub const DAYS: [Day; 91] = [
    Day { label: "Apr 1", desktop: 222, mobile: 150 },
    Day { label: "Apr 2", desktop: 97, mobile: 180 },
    Day { label: "Apr 3", desktop: 167, mobile: 120 },
    Day { label: "Apr 4", desktop: 242, mobile: 260 },
    Day { label: "Apr 5", desktop: 373, mobile: 290 },
    Day { label: "Apr 6", desktop: 301, mobile: 340 },
    Day { label: "Apr 7", desktop: 245, mobile: 180 },
    Day { label: "Apr 8", desktop: 409, mobile: 320 },
    Day { label: "Apr 9", desktop: 59, mobile: 110 },
    Day { label: "Apr 10", desktop: 261, mobile: 190 },
    Day { label: "Apr 11", desktop: 327, mobile: 350 },
    Day { label: "Apr 12", desktop: 292, mobile: 210 },
    Day { label: "Apr 13", desktop: 342, mobile: 380 },
    Day { label: "Apr 14", desktop: 137, mobile: 220 },
    Day { label: "Apr 15", desktop: 120, mobile: 170 },
    Day { label: "Apr 16", desktop: 138, mobile: 190 },
    Day { label: "Apr 17", desktop: 446, mobile: 360 },
    Day { label: "Apr 18", desktop: 364, mobile: 410 },
    Day { label: "Apr 19", desktop: 243, mobile: 180 },
    Day { label: "Apr 20", desktop: 89, mobile: 150 },
    Day { label: "Apr 21", desktop: 137, mobile: 200 },
    Day { label: "Apr 22", desktop: 224, mobile: 170 },
    Day { label: "Apr 23", desktop: 138, mobile: 230 },
    Day { label: "Apr 24", desktop: 387, mobile: 290 },
    Day { label: "Apr 25", desktop: 215, mobile: 250 },
    Day { label: "Apr 26", desktop: 75, mobile: 130 },
    Day { label: "Apr 27", desktop: 383, mobile: 420 },
    Day { label: "Apr 28", desktop: 122, mobile: 180 },
    Day { label: "Apr 29", desktop: 315, mobile: 240 },
    Day { label: "Apr 30", desktop: 454, mobile: 380 },
    Day { label: "May 1", desktop: 165, mobile: 220 },
    Day { label: "May 2", desktop: 293, mobile: 310 },
    Day { label: "May 3", desktop: 247, mobile: 190 },
    Day { label: "May 4", desktop: 385, mobile: 420 },
    Day { label: "May 5", desktop: 481, mobile: 390 },
    Day { label: "May 6", desktop: 498, mobile: 520 },
    Day { label: "May 7", desktop: 388, mobile: 300 },
    Day { label: "May 8", desktop: 149, mobile: 210 },
    Day { label: "May 9", desktop: 227, mobile: 180 },
    Day { label: "May 10", desktop: 293, mobile: 330 },
    Day { label: "May 11", desktop: 335, mobile: 270 },
    Day { label: "May 12", desktop: 197, mobile: 240 },
    Day { label: "May 13", desktop: 197, mobile: 160 },
    Day { label: "May 14", desktop: 448, mobile: 490 },
    Day { label: "May 15", desktop: 473, mobile: 380 },
    Day { label: "May 16", desktop: 338, mobile: 400 },
    Day { label: "May 17", desktop: 499, mobile: 420 },
    Day { label: "May 18", desktop: 315, mobile: 350 },
    Day { label: "May 19", desktop: 235, mobile: 180 },
    Day { label: "May 20", desktop: 177, mobile: 230 },
    Day { label: "May 21", desktop: 82, mobile: 140 },
    Day { label: "May 22", desktop: 81, mobile: 120 },
    Day { label: "May 23", desktop: 252, mobile: 290 },
    Day { label: "May 24", desktop: 294, mobile: 220 },
    Day { label: "May 25", desktop: 201, mobile: 250 },
    Day { label: "May 26", desktop: 213, mobile: 170 },
    Day { label: "May 27", desktop: 420, mobile: 460 },
    Day { label: "May 28", desktop: 233, mobile: 190 },
    Day { label: "May 29", desktop: 78, mobile: 130 },
    Day { label: "May 30", desktop: 340, mobile: 280 },
    Day { label: "May 31", desktop: 178, mobile: 230 },
    Day { label: "Jun 1", desktop: 178, mobile: 200 },
    Day { label: "Jun 2", desktop: 470, mobile: 410 },
    Day { label: "Jun 3", desktop: 103, mobile: 160 },
    Day { label: "Jun 4", desktop: 439, mobile: 380 },
    Day { label: "Jun 5", desktop: 88, mobile: 140 },
    Day { label: "Jun 6", desktop: 294, mobile: 250 },
    Day { label: "Jun 7", desktop: 323, mobile: 370 },
    Day { label: "Jun 8", desktop: 385, mobile: 320 },
    Day { label: "Jun 9", desktop: 438, mobile: 480 },
    Day { label: "Jun 10", desktop: 155, mobile: 200 },
    Day { label: "Jun 11", desktop: 92, mobile: 150 },
    Day { label: "Jun 12", desktop: 492, mobile: 420 },
    Day { label: "Jun 13", desktop: 81, mobile: 130 },
    Day { label: "Jun 14", desktop: 426, mobile: 380 },
    Day { label: "Jun 15", desktop: 307, mobile: 350 },
    Day { label: "Jun 16", desktop: 371, mobile: 310 },
    Day { label: "Jun 17", desktop: 475, mobile: 520 },
    Day { label: "Jun 18", desktop: 107, mobile: 170 },
    Day { label: "Jun 19", desktop: 341, mobile: 290 },
    Day { label: "Jun 20", desktop: 408, mobile: 450 },
    Day { label: "Jun 21", desktop: 169, mobile: 210 },
    Day { label: "Jun 22", desktop: 317, mobile: 270 },
    Day { label: "Jun 23", desktop: 480, mobile: 530 },
    Day { label: "Jun 24", desktop: 132, mobile: 180 },
    Day { label: "Jun 25", desktop: 141, mobile: 190 },
    Day { label: "Jun 26", desktop: 434, mobile: 380 },
    Day { label: "Jun 27", desktop: 448, mobile: 490 },
    Day { label: "Jun 28", desktop: 149, mobile: 200 },
    Day { label: "Jun 29", desktop: 103, mobile: 160 },
    Day { label: "Jun 30", desktop: 446, mobile: 400 },
];

#[derive(Clone, Copy, PartialEq)]
pub enum Status {
    Done,
    InProcess,
}

#[derive(Clone, Copy)]
pub struct Row {
    pub id: u32,
    pub header: &'static str,
    pub section_type: &'static str,
    pub status: Status,
    pub target: &'static str,
    pub limit: &'static str,
    pub reviewer: &'static str,
}

pub const ROWS: [Row; 68] = [
    Row {
        id: 1,
        header: "Cover page",
        section_type: "Cover page",
        status: Status::InProcess,
        target: "18",
        limit: "5",
        reviewer: "Eddie Lake",
    },
    Row {
        id: 2,
        header: "Table of contents",
        section_type: "Table of contents",
        status: Status::Done,
        target: "29",
        limit: "24",
        reviewer: "Eddie Lake",
    },
    Row {
        id: 3,
        header: "Executive summary",
        section_type: "Narrative",
        status: Status::Done,
        target: "10",
        limit: "13",
        reviewer: "Eddie Lake",
    },
    Row {
        id: 4,
        header: "Technical approach",
        section_type: "Narrative",
        status: Status::Done,
        target: "27",
        limit: "23",
        reviewer: "Jamik Tashpulatov",
    },
    Row {
        id: 5,
        header: "Design",
        section_type: "Narrative",
        status: Status::InProcess,
        target: "2",
        limit: "16",
        reviewer: "Jamik Tashpulatov",
    },
    Row {
        id: 6,
        header: "Capabilities",
        section_type: "Narrative",
        status: Status::InProcess,
        target: "20",
        limit: "8",
        reviewer: "Jamik Tashpulatov",
    },
    Row {
        id: 7,
        header: "Integration with existing systems",
        section_type: "Narrative",
        status: Status::InProcess,
        target: "19",
        limit: "21",
        reviewer: "Jamik Tashpulatov",
    },
    Row {
        id: 8,
        header: "Innovation and Advantages",
        section_type: "Narrative",
        status: Status::Done,
        target: "25",
        limit: "26",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 9,
        header: "Overview of EMR's Innovative Solutions",
        section_type: "Technical content",
        status: Status::Done,
        target: "7",
        limit: "23",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 10,
        header: "Advanced Algorithms and Machine Learning",
        section_type: "Narrative",
        status: Status::Done,
        target: "30",
        limit: "28",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 11,
        header: "Adaptive Communication Protocols",
        section_type: "Narrative",
        status: Status::Done,
        target: "9",
        limit: "31",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 12,
        header: "Advantages Over Current Technologies",
        section_type: "Narrative",
        status: Status::Done,
        target: "12",
        limit: "0",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 13,
        header: "Past Performance",
        section_type: "Narrative",
        status: Status::Done,
        target: "22",
        limit: "33",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 14,
        header: "Customer Feedback and Satisfaction Levels",
        section_type: "Narrative",
        status: Status::Done,
        target: "15",
        limit: "34",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 15,
        header: "Implementation Challenges and Solutions",
        section_type: "Narrative",
        status: Status::Done,
        target: "3",
        limit: "35",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 16,
        header: "Security Measures and Data Protection Policies",
        section_type: "Narrative",
        status: Status::InProcess,
        target: "6",
        limit: "36",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 17,
        header: "Scalability and Future Proofing",
        section_type: "Narrative",
        status: Status::Done,
        target: "4",
        limit: "37",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 18,
        header: "Cost-Benefit Analysis",
        section_type: "Plain language",
        status: Status::Done,
        target: "14",
        limit: "38",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 19,
        header: "User Training and Onboarding Experience",
        section_type: "Narrative",
        status: Status::Done,
        target: "17",
        limit: "39",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 20,
        header: "Future Development Roadmap",
        section_type: "Narrative",
        status: Status::Done,
        target: "11",
        limit: "40",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 21,
        header: "System Architecture Overview",
        section_type: "Technical content",
        status: Status::InProcess,
        target: "24",
        limit: "18",
        reviewer: "Maya Johnson",
    },
    Row {
        id: 22,
        header: "Risk Management Plan",
        section_type: "Narrative",
        status: Status::Done,
        target: "15",
        limit: "22",
        reviewer: "Carlos Rodriguez",
    },
    Row {
        id: 23,
        header: "Compliance Documentation",
        section_type: "Legal",
        status: Status::InProcess,
        target: "31",
        limit: "27",
        reviewer: "Sarah Chen",
    },
    Row {
        id: 24,
        header: "API Documentation",
        section_type: "Technical content",
        status: Status::Done,
        target: "8",
        limit: "12",
        reviewer: "Raj Patel",
    },
    Row {
        id: 25,
        header: "User Interface Mockups",
        section_type: "Visual",
        status: Status::InProcess,
        target: "19",
        limit: "25",
        reviewer: "Leila Ahmadi",
    },
    Row {
        id: 26,
        header: "Database Schema",
        section_type: "Technical content",
        status: Status::Done,
        target: "22",
        limit: "20",
        reviewer: "Thomas Wilson",
    },
    Row {
        id: 27,
        header: "Testing Methodology",
        section_type: "Technical content",
        status: Status::InProcess,
        target: "17",
        limit: "14",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 28,
        header: "Deployment Strategy",
        section_type: "Narrative",
        status: Status::Done,
        target: "26",
        limit: "30",
        reviewer: "Eddie Lake",
    },
    Row {
        id: 29,
        header: "Budget Breakdown",
        section_type: "Financial",
        status: Status::InProcess,
        target: "13",
        limit: "16",
        reviewer: "Jamik Tashpulatov",
    },
    Row {
        id: 30,
        header: "Market Analysis",
        section_type: "Research",
        status: Status::Done,
        target: "29",
        limit: "32",
        reviewer: "Sophia Martinez",
    },
    Row {
        id: 31,
        header: "Competitor Comparison",
        section_type: "Research",
        status: Status::InProcess,
        target: "21",
        limit: "19",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 32,
        header: "Maintenance Plan",
        section_type: "Technical content",
        status: Status::Done,
        target: "16",
        limit: "23",
        reviewer: "Alex Thompson",
    },
    Row {
        id: 33,
        header: "User Personas",
        section_type: "Research",
        status: Status::InProcess,
        target: "27",
        limit: "24",
        reviewer: "Nina Patel",
    },
    Row {
        id: 34,
        header: "Accessibility Compliance",
        section_type: "Legal",
        status: Status::Done,
        target: "18",
        limit: "21",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 35,
        header: "Performance Metrics",
        section_type: "Technical content",
        status: Status::InProcess,
        target: "23",
        limit: "26",
        reviewer: "David Kim",
    },
    Row {
        id: 36,
        header: "Disaster Recovery Plan",
        section_type: "Technical content",
        status: Status::Done,
        target: "14",
        limit: "17",
        reviewer: "Jamik Tashpulatov",
    },
    Row {
        id: 37,
        header: "Third-party Integrations",
        section_type: "Technical content",
        status: Status::InProcess,
        target: "25",
        limit: "28",
        reviewer: "Eddie Lake",
    },
    Row {
        id: 38,
        header: "User Feedback Summary",
        section_type: "Research",
        status: Status::Done,
        target: "20",
        limit: "15",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 39,
        header: "Localization Strategy",
        section_type: "Narrative",
        status: Status::InProcess,
        target: "12",
        limit: "19",
        reviewer: "Maria Garcia",
    },
    Row {
        id: 40,
        header: "Mobile Compatibility",
        section_type: "Technical content",
        status: Status::Done,
        target: "28",
        limit: "31",
        reviewer: "James Wilson",
    },
    Row {
        id: 41,
        header: "Data Migration Plan",
        section_type: "Technical content",
        status: Status::InProcess,
        target: "19",
        limit: "22",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 42,
        header: "Quality Assurance Protocols",
        section_type: "Technical content",
        status: Status::Done,
        target: "30",
        limit: "33",
        reviewer: "Priya Singh",
    },
    Row {
        id: 43,
        header: "Stakeholder Analysis",
        section_type: "Research",
        status: Status::InProcess,
        target: "11",
        limit: "14",
        reviewer: "Eddie Lake",
    },
    Row {
        id: 44,
        header: "Environmental Impact Assessment",
        section_type: "Research",
        status: Status::Done,
        target: "24",
        limit: "27",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 45,
        header: "Intellectual Property Rights",
        section_type: "Legal",
        status: Status::InProcess,
        target: "17",
        limit: "20",
        reviewer: "Sarah Johnson",
    },
    Row {
        id: 46,
        header: "Customer Support Framework",
        section_type: "Narrative",
        status: Status::Done,
        target: "22",
        limit: "25",
        reviewer: "Jamik Tashpulatov",
    },
    Row {
        id: 47,
        header: "Version Control Strategy",
        section_type: "Technical content",
        status: Status::InProcess,
        target: "15",
        limit: "18",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 48,
        header: "Continuous Integration Pipeline",
        section_type: "Technical content",
        status: Status::Done,
        target: "26",
        limit: "29",
        reviewer: "Michael Chen",
    },
    Row {
        id: 49,
        header: "Regulatory Compliance",
        section_type: "Legal",
        status: Status::InProcess,
        target: "13",
        limit: "16",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 50,
        header: "User Authentication System",
        section_type: "Technical content",
        status: Status::Done,
        target: "28",
        limit: "31",
        reviewer: "Eddie Lake",
    },
    Row {
        id: 51,
        header: "Data Analytics Framework",
        section_type: "Technical content",
        status: Status::InProcess,
        target: "21",
        limit: "24",
        reviewer: "Jamik Tashpulatov",
    },
    Row {
        id: 52,
        header: "Cloud Infrastructure",
        section_type: "Technical content",
        status: Status::Done,
        target: "16",
        limit: "19",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 53,
        header: "Network Security Measures",
        section_type: "Technical content",
        status: Status::InProcess,
        target: "29",
        limit: "32",
        reviewer: "Lisa Wong",
    },
    Row {
        id: 54,
        header: "Project Timeline",
        section_type: "Planning",
        status: Status::Done,
        target: "14",
        limit: "17",
        reviewer: "Eddie Lake",
    },
    Row {
        id: 55,
        header: "Resource Allocation",
        section_type: "Planning",
        status: Status::InProcess,
        target: "27",
        limit: "30",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 56,
        header: "Team Structure and Roles",
        section_type: "Planning",
        status: Status::Done,
        target: "20",
        limit: "23",
        reviewer: "Jamik Tashpulatov",
    },
    Row {
        id: 57,
        header: "Communication Protocols",
        section_type: "Planning",
        status: Status::InProcess,
        target: "15",
        limit: "18",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 58,
        header: "Success Metrics",
        section_type: "Planning",
        status: Status::Done,
        target: "30",
        limit: "33",
        reviewer: "Eddie Lake",
    },
    Row {
        id: 59,
        header: "Internationalization Support",
        section_type: "Technical content",
        status: Status::InProcess,
        target: "23",
        limit: "26",
        reviewer: "Jamik Tashpulatov",
    },
    Row {
        id: 60,
        header: "Backup and Recovery Procedures",
        section_type: "Technical content",
        status: Status::Done,
        target: "18",
        limit: "21",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 61,
        header: "Monitoring and Alerting System",
        section_type: "Technical content",
        status: Status::InProcess,
        target: "25",
        limit: "28",
        reviewer: "Daniel Park",
    },
    Row {
        id: 62,
        header: "Code Review Guidelines",
        section_type: "Technical content",
        status: Status::Done,
        target: "12",
        limit: "15",
        reviewer: "Eddie Lake",
    },
    Row {
        id: 63,
        header: "Documentation Standards",
        section_type: "Technical content",
        status: Status::InProcess,
        target: "27",
        limit: "30",
        reviewer: "Jamik Tashpulatov",
    },
    Row {
        id: 64,
        header: "Release Management Process",
        section_type: "Planning",
        status: Status::Done,
        target: "22",
        limit: "25",
        reviewer: "Assign reviewer",
    },
    Row {
        id: 65,
        header: "Feature Prioritization Matrix",
        section_type: "Planning",
        status: Status::InProcess,
        target: "19",
        limit: "22",
        reviewer: "Emma Davis",
    },
    Row {
        id: 66,
        header: "Technical Debt Assessment",
        section_type: "Technical content",
        status: Status::Done,
        target: "24",
        limit: "27",
        reviewer: "Eddie Lake",
    },
    Row {
        id: 67,
        header: "Capacity Planning",
        section_type: "Planning",
        status: Status::InProcess,
        target: "21",
        limit: "24",
        reviewer: "Jamik Tashpulatov",
    },
    Row {
        id: 68,
        header: "Service Level Agreements",
        section_type: "Legal",
        status: Status::Done,
        target: "26",
        limit: "29",
        reviewer: "Assign reviewer",
    },
];

pub struct Metric {
    pub title: &'static str,
    pub delta: &'static str,
    pub up: bool,
    pub value: &'static str,
    pub foot: &'static str,
    pub foot_up: bool,
    pub sub: &'static str,
}

pub const METRICS: [Metric; 4] = [
    Metric {
        title: "Total Revenue",
        delta: "+12.5%",
        up: true,
        value: "$1,250.00",
        foot: "Trending up this month",
        foot_up: true,
        sub: "Visitors for the last 6 months",
    },
    Metric {
        title: "New Customers",
        delta: "-20%",
        up: false,
        value: "1,234",
        foot: "Down 20% this period",
        foot_up: false,
        sub: "Acquisition needs attention",
    },
    Metric {
        title: "Active Accounts",
        delta: "+12.5%",
        up: true,
        value: "45,678",
        foot: "Strong user retention",
        foot_up: true,
        sub: "Engagement exceed targets",
    },
    Metric {
        title: "Growth Rate",
        delta: "+4.5%",
        up: true,
        value: "4.5%",
        foot: "Steady performance increase",
        foot_up: true,
        sub: "Meets growth projections",
    },
];
